package-lock.json
package.json

Support 15019 add dev mode config to proxy api requests

---

components/resource-select/__tests__/ResourceSelect.test.tsx
components/table/__tests__/QueryTable.test.tsx
package.json

https://redmine.biodiversity.agr.gc.ca/issues/15498
-Added type check before tests.
-Fixed existing Typescript errors in tests.

Feedback Support #15498 Run type check before tests

---

README.md
docs/getting_started.adoc
docs/index.adoc

https://redmine.biodiversity.agr.gc.ca/issues/16536
* Updated the Readme with getting started information.
* Updated the developer documentation with detailed installation instructions.

Support #16536 - Update Installation Documentation

---

pages/_app.tsx

https://redmine.biodiversity.agr.gc.ca/issues/16472
-Added check for whether the app is on the error page to prevent
it from repeatedly refereshing.

Feedback Bug #16472 404 page refreshing itself

---

components/index.ts
components/list-page-layout/ListPageLayout.tsx
components/table/QueryTable.tsx
components/table/__tests__/QueryTable.test.tsx
page-tests/pcr-primer/__tests__/list.test.tsx
page-tests/product/__tests__/list.test.tsx
page-tests/protocol/__tests__/list.test.tsx
pages/pcr-primer/list.tsx
pages/pcr-profile/list.tsx
pages/product/list.tsx
pages/protocol/list.tsx

https://redmine.biodiversity.agr.gc.ca/issues/16567
-Added generic list page component.
-Converted the list pages to use this component.

Feedback Feature #16567 Generic list page layout component

---

components/api-client/ApiClientContext.ts
components/api-client/__tests__/ApiClientContext.test.ts
pages/pcr-primer/edit.tsx
pages/pcr-profile/edit.tsx
pages/product/edit.tsx
pages/protocol/edit.tsx
pages/region/edit.tsx

https://redmine.biodiversity.agr.gc.ca/issues/16813
-Moved save logic into a "save" function in the ApiClientContext.
-Changed the form submit functions to use the save function.
-Added tests for the save function.

Feedback Support #16813 Add convenience method for saving resources

---

components/api-client/ApiClientContext.ts
components/api-client/__tests__/ApiClientContext.test.ts

https://redmine.biodiversity.agr.gc.ca/issues/16854
- Added crnk-compact to the Query headers.

Support #16854 - Use Crnk-Compact for UI API queries

---

packages/objectstore-ui/components/metadata/MetadataDetails.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19350
Changed the tag color to yellow.

Feedback Support #19350 Improve the tag color in Obectstore UI

---

packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/intl/dina-ui-en.ts

https://redmine.biodiversity.agr.gc.ca/issues/19578
Added feedback button to the nav bar.

Feedback Support #19578 Add a Feedback button to all pages

---

packages/dina-ui/pages/agent/edit.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19520
-Added delete button.

Feedback Support #19520 Add delete button for Agent

---

packages/dina-ui/pages/agent/list.tsx
packages/dina-ui/pages/agent/view.tsx
packages/dina-ui/types/objectstore-api/resources/Agent.ts

https://redmine.biodiversity.agr.gc.ca/issues/19530
-Added new fields to typescript type, list page and single agent details page.
-Fixed cancel button URL on agent details page.

Support #19530 Display Agent createdBy and createdOn

---

packages/dina-ui/components/stored-object-gallery/StoredObjectGallery.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19577
-Added alternative text when there is no thumbnail.

Support_19577_Display_alternative_text_when_thumbails_is_not_available

---

Dockerfile
seqdb-ui.Dockerfile

https://redmine.biodiversity.agr.gc.ca/issues/19696
-Fixed Dockerfiles so they work with OKD.

Feedback Bug #19696 Change dina-ui Dockerfile so it can build on OKD

---

packages/common-ui/lib/button-bar/DeleteButton.tsx
packages/dina-ui/pages/object-store/managedAttributesView/detailsView.tsx
packages/dina-ui/pages/object-store/object-subtype/edit.tsx
packages/dina-ui/pages/object-store/object/view.tsx
packages/dina-ui/pages/person/edit.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19802
-Moved delete button to the right of the other buttons, with extra spacing.

Feedback Support #19802 Move delete button

---

Dockerfile
seqdb-ui.Dockerfile

https://redmine.biodiversity.agr.gc.ca/issues/19874
-Added tsconfig.common.json copy line to Dockerfiles.

Feedback Bug #19874 Docker build fails

---

packages/common-ui/lib/button-bar/DeleteButton.tsx
packages/dina-ui/pages/object-store/object-subtype/edit.tsx
packages/dina-ui/types/objectstore-api/resources/ObjectSubtype.ts

https://redmine.biodiversity.agr.gc.ca/issues/19870
-Added 'disabled' prop to DeleteButton.
-Made the delete button disabled on app managed subtype.

Feedback Support #19870 Prevent deletion of app managed Object SubType

---

packages/common-ui/lib/bulk-data-editor/resource-select-cell.ts
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/object-store/metadata/__tests__/edit.test.tsx
packages/dina-ui/pages/object-store/metadata/edit.tsx
packages/dina-ui/types/objectstore-api/index.ts
packages/dina-ui/types/objectstore-api/resources/License.ts
packages/dina-ui/types/objectstore-api/resources/Metadata.ts

-Added License dropdown to the bulk Metadata editor.
-Added test for the License column.

Feedback 20213

---

packages/common-ui/lib/formik-connected/SelectField.tsx
packages/common-ui/lib/resource-select/ResourceSelect.tsx

- Fixed by removing zindex style

Support_20285_ResourceSelect_component_style_related_issues

---

packages/common-ui/lib/intl/common-ui-en.ts
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/tooltip/Tooltip.tsx
packages/dina-ui/pages/object-store/object/list.tsx

-Changed Tooltip component so it can use a different initial visible element.
-Added tooltip to the QueryTable to explain multi-sort.

Feedback 20363

---

packages/dina-ui/components/file-upload/FileUploader.tsx
packages/dina-ui/page-tests/object-store/__tests__/upload.test.tsx
packages/dina-ui/pages/object-store/upload.tsx

-Added acDigitizationDate on file upload.
-Updated test.

Feedback 20511

---

packages/dina-ui/pages/object-store/object/list.tsx

Removed dcFormat field from stored object list

Feedback 20500

---

packages/dina-ui/pages/object-store/object/list.tsx

Added xmpMetadataDate date filter.

Feedback 20498

---

packages/dina-ui/page-tests/object-store/object/__tests__/list.test.tsx
packages/dina-ui/pages/object-store/object/list.tsx

Added the hyperlink to the image name in the table.

Feedback 20499

---

packages/dina-ui/pages/object-store/object-subtype/list.tsx

-Added createdOn/By to ObjectSubtype list page.

Feedback 20648

---

packages/common-ui/lib/formik-connected/DateField.tsx
packages/dina-ui/pages/object-store/object-subtype/edit.tsx

-Added w-100 class to datepicker so it fits the FieldWrapper width.
-Added createdOn/By to subtype edit/view page.

Feedback 20681

---

packages/common-ui/package.json
packages/dina-ui/next.config.js
packages/dina-ui/package.json
packages/seqdb-ui/next.config.js
packages/seqdb-ui/package.json
yarn.lock

-Updated nextjs to v10.
-Updated next-transpile-modules to v4.

20677 Update object-path

---

packages/dina-ui/pages/object-store/metadata/edit.tsx

Added dcRights and xmpRightsWebStatement to metadata editor.

Support #20860 Rights Statement should be editable

---

packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/pages/index.tsx

Support 20887 Hide Dina user UI util user api module is ready

---

packages/common-ui/lib/date/DateView.tsx
packages/common-ui/lib/date/__tests__/DateView.test.tsx
packages/common-ui/lib/index.ts
packages/common-ui/lib/table/date-cell.tsx
packages/dina-ui/components/metadata/MetadataDetails.tsx
packages/dina-ui/components/revisions/RevisionsPageLayout.tsx
packages/dina-ui/components/revisions/revision-row-configs/metadata-revision-row-config.tsx
packages/seqdb-ui/pages/pcr-primer/view.tsx

-Added common DateView component.
-Changed remaining date fields to use DateView.

Support #20900 Date display should be consistent

---

Dockerfile

- Remove the line that  refer to file does not exist anymore

Support #21098 Fix broken Dockerfile

---

packages/common-ui/lib/intl/LanguageSelector.tsx

- Fix the language parts in language toggle button as well as the page lang attribute

Support 21090 wcag issue   3.1.2 language of parts (level aa) and 3.1.1 language of page (level a)

---

packages/dina-ui/components/seqdb/workflow/pre-library-prep/PreLibraryPrepBulkEdit.tsx

Added condition to omit rsql if there are no Samples selected in the previous step. Fixes the error when there are no Samples selected.

Feedback 21100

---

.dockerignore
Dockerfile

Changed Dockerfile to work from the output of yarn install

21195 Remove multistage build from Dockerfile dina-ui

---

packages/common-ui/lib/bulk-data-editor/BulkDataEditor.tsx
packages/common-ui/lib/bulk-data-editor/__tests__/useBulkEditorFrontEndValidation.test.tsx
packages/common-ui/lib/bulk-data-editor/useBulkEditorFrontEndValidation.tsx
packages/common-ui/lib/intl/common-ui-en.ts

-Added error message and disabed the submit button when there is a validation error.
-Added numbered rows to the table so the error tells which row has the error.

Feedback 21136

---

packages/common-ui/lib/intl/LanguageSelector.tsx
packages/dina-ui/components/button-bar/nav/nav.tsx

- Adjust Feedback and language button to be above 4.5:1 contrast ratio

Support 21230 ISB EIS WCAG2, 1.4.3 Contrast (Minimum)

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/object-store/managedAttributesView/detailsView.tsx
packages/dina-ui/types/objectstore-api/resources/ManagedAttribute.ts

- Change detail view to have fields of Integer, Text and Pick List
- Use bilingual labels for the dropdown  items

Support 21221Renamed fields in managed attributes view

---

packages/dina-ui/pages/object-store/metadata/edit.tsx

- Update  metadata bulk edit page to navigate to detail page when there is single record

Support 21278 Edit single Metadata navigation issue

---

packages/dina-ui/pages/object-store/managedAttributesView/detailsView.tsx
packages/dina-ui/pages/object-store/managedAttributesView/listView.tsx
packages/dina-ui/types/objectstore-api/resources/ManagedAttribute.ts

-Updated table and detailsView to show the same attribute type labels.

Feedback 21301

---

packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/pages/index.tsx

- Hide from navigation and index page

Support 21349 Hide collection module

---

packages/dina-ui/pages/collecting-event/edit.tsx
packages/dina-ui/pages/collecting-event/list.tsx
packages/dina-ui/pages/collecting-event/view.tsx

- Add group to list, edit and view pages

Support 21380 Add group to collecting-event view

---

packages/common-ui/lib/api-client/useQuery.tsx
packages/dina-ui/pages/object-store/metadata/single-record-edit.tsx

-Fixed useQuery  to finish the onSuccess callback before returning the query result.
-Made the acDigitizationDate editable.

Feedback 21427

---

packages/dina-ui/intl/dina-ui-en.ts

Renamed "Metadata Created By" to "Uploaded By".

Feedback 21433

---

packages/common-ui/lib/bulk-data-editor/BulkDataEditor.tsx
packages/dina-ui/components/object-store/attachment-list/useBulkMetadataEditModal.tsx

-Improved css for scrolling large data sets in the bulk edit modal.
-Added css and spacer div to make sure the dropdowns show properly.

Feedback 21438

---

packages/common-ui/lib/intl/common-ui-en.ts
packages/dina-ui/components/object-store/metadata-bulk-editor/BulkMetadataEditor.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/object-store/metadata/single-record-edit.tsx

-Added publiclyReleasable and notPubliclyReleasableReason to bulk editor.
-Added notPubliclyReleasableReason to single record edit.

Feedback 21436

---

packages/dina-ui/pages/collecting-event/edit.tsx

Replaced apiClient call with bulkGet call.

Feedback 21450

---

Dockerfile

- Update caddy to 2.3.0 in Docker file

Support 21446 Update Caddy version

---

packages/dina-ui/pages/collecting-event/list.tsx

Fixed variable precision collection event table date cells to show the string as is.

Feedback 21478

---

package.json
yarn.lock

Couldn't update kitsu because of breaking changes in newer versions, so updated axios version using yarn resolutions property.

Feedback 21489

---

packages/common-ui/lib/bulk-data-editor/resource-select-cell.ts
packages/common-ui/lib/intl/common-ui-en.ts
packages/common-ui/lib/resource-select/ResourceSelect.tsx
packages/common-ui/lib/resource-select/__tests__/ResourceSelect.test.tsx

Added placeholder text. Used same text in the ResourceSelect component.

Feedback 20299

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts

Feedback 21521

---

packages/dina-ui/components/object-store/metadata-bulk-editor/BulkMetadataEditor.tsx
packages/dina-ui/components/object-store/stored-object-gallery/StoredObjectGallery.tsx
packages/dina-ui/page-tests/object-store/metadata/__tests__/edit.test.tsx

-Changed GalleryItem link from filename to acCaption.
-Set default caption to originalFilename.

Feedback 21578

---

packages/dina-ui/intl/dina-ui-en.ts

Feedback 21582

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts

-Renamed dcRights to Copyright.

Feedback 21585

---

packages/common-ui/lib/account/NavBarUserControl.tsx
packages/common-ui/lib/intl/common-ui-en.ts
packages/common-ui/lib/intl/common-ui-fr.ts
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/dina-user/__test__/view.test.tsx
packages/dina-ui/pages/dina-user/view.tsx
packages/dina-ui/pages/index.tsx

-Fixed user link so only the username is a link.
-Removed Whoami link from home page.
-Removed unnecessary fields from user view page, kept link to the associated person page.

Feedback 21620

---

packages/common-ui/lib/resource-select/ResourceSelect.tsx
packages/common-ui/package.json
yarn.lock

-Added drag/drop support to the ResourceSelect dropdowns.

Feedback Support #21605 Reorder agent Collectors

---

packages/common-ui/lib/modal/__tests__/modal.test.tsx
packages/common-ui/lib/modal/modal.tsx
packages/dina-ui/components/object-store/attachment-list/useBulkMetadataEditModal.tsx

-Changed modal state from one element to an array.
-Added test for multiple modals.
-Fixed some styling when multiple modals are open.

Feedback 21650

---

packages/common-ui/lib/api-client/ApiClientContext.tsx
packages/common-ui/lib/api-client/__tests__/ApiClientContext.test.ts
packages/common-ui/lib/formik-connected/ErrorViewer.tsx
packages/common-ui/lib/modal/AreYouSureModal.tsx

-Added handling for Spring Boot's error response structure to show the whole error message to the user.

Feedback 21595

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collecting-event/edit.tsx
packages/dina-ui/pages/collecting-event/view.tsx

Added Collector's Number field

Support_21735_Add_Collectors_Number_to_collecting_event

---

packages/common-ui/lib/formik-connected/SubmitButton.tsx
packages/common-ui/lib/list-page-layout/ListPageLayout.tsx
packages/common-ui/lib/table/date-cell.tsx
packages/dina-ui/components/object-store/attachment-list/AttachmentSection.tsx
packages/dina-ui/components/object-store/attachment-list/ExistingAttachmentsTable.tsx
packages/dina-ui/components/object-store/attachment-list/ExistingObjectsAttacher.tsx
packages/dina-ui/components/object-store/attachment-list/__tests__/ExistingObjectsAttacher.test.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collecting-event/view.tsx
packages/dina-ui/pages/object-store/object/list.tsx
yarn.lock

Support_21720_Allow_to_attach_existing_objects_in_collecting-event_attachment

---

packages/common-ui/lib/api-client/ApiClientContext.tsx
packages/common-ui/lib/resource-select/ResourceSelect.tsx
packages/common-ui/lib/resource-select/__tests__/ResourceSelect.test.tsx
packages/dina-ui/components/add-person/PersonForm.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collecting-event/edit.tsx

-Added tests.
-Updated label prop comment.
-Changed option label to "Add New Person".

Support_21734_Add_option_to_Add_New_Agent_in_Collectors_dropdown

---

packages/dina-ui/intl/dina-ui-en.ts

Support_21725_Add_tooltips_to_verbatim_location_fields

---

packages/common-ui/lib/formik-connected/FieldView.tsx
packages/common-ui/lib/formik-connected/__tests__/FieldView.test.tsx
packages/dina-ui/page-tests/dina-user/__test__/view.test.tsx
packages/dina-ui/page-tests/organization/__tests__/view.test.tsx
packages/dina-ui/pages/collecting-event/view.tsx

-Changed the FieldView to add a space to the comma-separated lists.
-Stuck the verbatimEventDateTime field to the bottom of the row div.
-Updated tests.

Feedback 21759

---

packages/common-ui/lib/tooltip/Tooltip.tsx
packages/dina-ui/intl/dina-ui-en.ts

-Combined tooltip messages for verbatim locality and latitude
-Adjust tooltip component so that linefeed within message is reflected

 Support-21779-Dina-ui-dev-branch-broken

---

packages/common-ui/lib/keyboard-event-handler/KeyboardEventHandlerWrappedTextField.tsx
packages/dina-ui/intl/dina-ui-en.ts

-Changed double apostrophe to a quote.

Feedback 21795

---

packages/dina-ui/components/collection/GeoReferenceAssertionRow.tsx
packages/dina-ui/components/collection/__tests__/ViewInMapButton.test.tsx
packages/dina-ui/intl/dina-ui-en.ts

Support_21924_Add_View_On_Map_button

---

packages/common-ui/lib/field-header/FieldHeader.tsx
packages/common-ui/lib/formik-connected/FieldWrapper.tsx
packages/dina-ui/components/collection/GeoReferenceAssertionRow.tsx
packages/dina-ui/intl/dina-ui-en.ts

-Added new field.
-Added comment to customName prop.

Feedback 21999

---

packages/dina-ui/pages/collecting-event/edit.tsx
packages/dina-ui/pages/collecting-event/view.tsx

-Ordered the assertions by createdOn.
-Fixed the assertion list on the view page so it doesn't show a 0 when there are no assertions (This was probably caused again by change 1).

Feedback 22003

---

packages/common-ui/lib/formik-connected/DateField.tsx
packages/dina-ui/components/collection/GeoReferenceAssertionRow.tsx

- Removed withZone prop and its usage

Support 22000 Change GeoreferencedDate to LocalDate

---

packages/dina-ui/components/collection/GeographySearchDialog.tsx

- Remove filter to allow search results

Support-22083-Search-by-"Central-Experimental-Farm"-return-no-result

---

packages/common-ui/lib/formik-connected/NumberField.tsx
packages/dina-ui/components/collection/GeoReferenceAssertionRow.tsx
packages/dina-ui/components/collection/__tests__/GeoReferenceAssertionRow.test.tsx

Added validation preventing input of invalid lat/lon values in GeoReferenceAssertion section.

Feedback 22098

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx

-Moved VerbatimLocality field into left row.
-Hid numbered tabs when there is 1 Assertion.
-Hid the links to search by location fields instead of disabling them.

Feedback 22246

---

packages/common-ui/lib/formik-connected/CheckBoxField.tsx
packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/GeographySearchBox.tsx
packages/dina-ui/pages/collection/collecting-event/edit.tsx

-Replaced useFormikContext usage with FormikButton and Field usage.
Using the React dev tools profiler should show that the entire form isn't rendering on every keypress.

Feedback 22241

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx

- Remove this section in current geographic places

Support-22276--remove-serach-by-verbatime-lat/long

---

packages/dina-ui/pages/object-store/object-subtype/edit.tsx

- Removed the disable attribute on delete button which depends on app managed

Support-22341-remove-usage-of-app-managed-on-object-sub-type

---

packages/dina-ui/components/object-store/metadata/MetadataDetails.tsx
packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/object-store/metadata/MetadataPreview.tsx
packages/dina-ui/pages/object-store/metadata/single-record-edit.tsx
packages/dina-ui/pages/object-store/object/view.tsx
packages/dina-ui/types/objectstore-api/index.ts
packages/dina-ui/types/objectstore-api/resources/Derivative.ts
packages/dina-ui/types/objectstore-api/resources/Metadata.ts

-Refactored to remove duplicates of metadata querying and file viewing code.
-Added check for LARGE_IMAGE derivative type. This should display in the list page preview panel, and the single Metadata's view and edit pages.

Feedback 22392

---

packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/object-store/metadata/__tests__/MetadataFileView.test.tsx

-Added "derivative/" to derivative urls.
-Added MetadataFileView tests.

Feedback 22433

---

packages/common-ui/lib/formik-connected/FormikButton.tsx
packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/GeoReferenceAssertionRow.tsx
packages/dina-ui/components/collection/useCollectingEvent.ts
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/collection/catalogued-object/__tests__/edit.test.tsx
packages/dina-ui/page-tests/collection/collecting-event/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/collecting-event/__test__/view.test.tsx
packages/dina-ui/types/collection-api/resources/GeoReferenceAssertion.ts

-Added Make Primary button and Primary indicator in the tab text, updated form code to add isPrimary attribute.
-Added test.

Feedback 22201

---

packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/object-store/metadata/__tests__/MetadataFileView.test.tsx
packages/dina-ui/intl/dina-ui-en.ts

-Added file type "Showing {Original / Large Image / Thumnail}" and caption below the file view.

Feedback 22486

---

packages/dina-ui/components/collection/useCollectingEvent.ts
packages/dina-ui/page-tests/collection/catalogued-object/__tests__/edit.test.tsx
packages/dina-ui/page-tests/collection/catalogued-object/__tests__/view.test.tsx
packages/dina-ui/pages/collection/catalogued-object/edit.tsx
packages/dina-ui/pages/collection/catalogued-object/list.tsx
packages/dina-ui/pages/collection/catalogued-object/view.tsx
packages/dina-ui/types/collection-api/index.ts
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

Renamed Physical Entity to Material Sample.

Feedback 22489

---

packages/common-ui/lib/formik-connected/DinaForm.tsx
packages/dina-ui/components/collection/CollectingEventFormLayout.tsx

-Added initialValues to dina form context.
-Made the Collecting Event form open with the primary assertion's tab open.

Feedback 22522

---

docs/docker_build.adoc
docs/intl.adoc
docs/resource_select_field.adoc
docs/useQuery_hook_function.adoc
docs/write_operations.adoc
docs/yarn_package_scripts.adoc

Fixed outdated parts of the docs.

Feedback 22593

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Add the new fieldset group
- Fix the duplicate message entries that failed in dev branch ci

Support 22625 make a new fieldset group for habitat

---

packages/common-ui/lib/formik-connected/SelectField.tsx
packages/common-ui/lib/resource-select/ResourceSelect.tsx
packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesEditor.tsx

- Fix Image must have alternate text
- Fix Element must have label
- Fix Elements must have sufficient color contrast

Support 22633 WCAG issue objectstore metadata single record edit page

---

packages/common-ui/lib/formik-connected/ErrorViewer.tsx
packages/common-ui/lib/formik-connected/__tests__/ErrorViewer.test.tsx

Call scrollIntoView when a new error appears.

Feedback 22664

---

packages/common-ui/lib/filter-builder/FilterRow.tsx

- Fix Elements must only use allowed ARIA attributes

Support 22644 WCAG issue object store metadata attribute list page

---

packages/common-ui/lib/modal/modal.tsx
packages/dina-ui/components/object-store/attachment-list/attachments-modal.tsx
packages/dina-ui/components/object-store/attachment-list/useBulkMetadataEditModal.tsx
packages/dina-ui/components/object-store/metadata-bulk-editor/custom-default-values/useDefaultValueRuleBuilderModal.tsx

-Added css to make sure you can scroll down modals when they get too big. This was in some modals already, but moved the CSS so all modals use it.

Feedback 22713

---

packages/dina-ui/components/seqdb/workflow/library-prep/container-grid/ContainerGrid.tsx
packages/dina-ui/components/seqdb/workflow/library-prep/container-grid/DraggableSampleBox.tsx
packages/dina-ui/components/seqdb/workflow/library-prep/container-grid/DraggableSampleList.tsx

Changed drag/drop keys to be the same string.

Feedback 22716

---

packages/dina-ui/components/object-store/attachment-list/attachments-modal.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

-Added Identifiers section.
-Added Preparations section.
-Added Error message when both material sample ID and catalog number is blank.
Certain fieldds are disabled because there is no back-end for them: "Other IDs", "Prepared By", "Date Prepared".,

In progress 22749

---

packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesEditor.tsx
packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesViewer.tsx
packages/dina-ui/components/object-store/managed-attributes/getManagedAttributesInUse.ts
packages/dina-ui/components/object-store/metadata-bulk-editor/BulkMetadataEditor.tsx
packages/dina-ui/components/object-store/metadata/MetadataDetails.tsx
packages/dina-ui/components/object-store/metadata/MetadataPreview.tsx
packages/dina-ui/components/object-store/metadata/__tests__/MetadataDetails.test.tsx
packages/dina-ui/page-tests/object-store/metadata/__tests__/edit.test.tsx
packages/dina-ui/page-tests/object-store/metadata/__tests__/single-record-edit.test.tsx
packages/dina-ui/page-tests/object-store/object/__tests__/view.test.tsx
packages/dina-ui/pages/object-store/metadata/single-record-edit.tsx
packages/dina-ui/types/objectstore-api/resources/Metadata.ts

-Changed Managed attribute editors and viewers to use the new schema.
-Updated tests.

Feedback 22754

---

packages/dina-ui/components/object-store/attachment-list/AttachmentUploader.tsx
packages/dina-ui/components/object-store/file-upload/FileUploader.tsx
packages/dina-ui/components/object-store/file-upload/__tests__/FileUploader.test.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/object-store/__tests__/upload.test.tsx
packages/dina-ui/pages/object-store/upload.tsx

-Removed the file type restriction and label.

Feedback 22747

---

docs/docker_build.adoc
packages/dina-ui/dev.Caddyfile
packages/dina-ui/prod.Caddyfile

-Added DISABLE_BROWSER_CHECK property to allow disabling the IE11 blocker.
-Updated UI Docker docs.

Feedback 22815

---

packages/dina-ui/pages/collection/preparation-type/list.tsx

-Added group filter and column to preparation type list.

Feedback 22839

---

packages/dina-ui/pages/collection/managed-attribute/edit.tsx
packages/dina-ui/pages/object-store/managedAttributesView/detailsView.tsx

-Added key field to managed attribute pages.
-Improved managed attribute page layouts.

Feedback 22828

---

packages/common-ui/lib/table/__tests__/stringArrayCell.test.tsx
packages/common-ui/lib/table/stringArray-cell.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

-Added dwcOtherCatalogNumbers field to edit / view / list pages.
-Added a space after the comma in stringArrayCell function.

Feedback 22841

---

packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesEditor.tsx
packages/dina-ui/components/object-store/managed-attributes/__tests__/ManagedAttributesEditor.test.tsx
packages/dina-ui/intl/dina-ui-en.ts

-Changed how the Managed Attribute Editor works so it removed the value when the attribute name is removed from the dropdown menu. There is a modal confiirmation before the value is removed.
-Added test.

Feedback 22846

---

packages/common-ui/lib/table/react-table-style.css
packages/dina-ui/components/collection/useMaterialSample.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

-Added MaterialSampleType field to material sample pages.
-Fixed table header text alignment.

Feedback 23015

---

packages/common-ui/lib/formik-connected/NumberField.tsx
packages/dina-ui/components/collection/CollectingEventFormLayout.tsx

-Made NumberField work for integers.
-Added the 2 new fields to the Col Event form.

Feedback 23120

---

packages/common-ui/lib/formik-connected/GroupedCheckBoxFields.tsx
packages/common-ui/lib/table/react-table-style.css
packages/dina-ui/pages/object-store/object/list.tsx

To fix WCAG label and contrast issues occurring in table header and columns on the preview page, preview pane, and details page

updates applied to stored objects page 

---

packages/dina-ui/components/object-store/metadata-bulk-editor/BulkMetadataEditor.tsx
packages/dina-ui/types/objectstore-api/resources/ObjectUpload.ts

-Removed the part where "orientation" is taken from the ObjectUpload, which doesn't have it.

Feedback 23348

---

packages/common-ui/common-ui-style.css

...without affecting autcomplete function

Update to fix contrast issues for input elements

---

packages/dina-ui/components/collection/PreparationField.tsx
packages/dina-ui/components/collection/useMaterialSample.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/page-tests/collection/material-sample/workflows/__tests__/split-run.test.tsx
packages/dina-ui/page-tests/collection/workflow-template/__tests__/run.test.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx
packages/dina-ui/pages/collection/material-sample/workflows/split-run.tsx
packages/dina-ui/pages/collection/workflow-template/edit.tsx
packages/dina-ui/types/collection-api/index.ts
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

-Moved/Renamed Preparation section into separate FIeld component.
-Moved preparation field names into a single place instead of re-listing them in different areas.
-Moved MaterialSampleType dropdown into the Preparation section.
-Added preparationRemarks field.

Feedback 23374

---

packages/dina-ui/components/storage/BrowseStorageTree.tsx
packages/dina-ui/components/storage/StorageUnitBreadCrumb.tsx
packages/dina-ui/components/storage/__tests__/AssignedStorage.test.tsx
packages/dina-ui/components/storage/__tests__/BrowseStorageTree.test.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitBreadCrumb.test.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitChildrenViewer.test.tsx
packages/dina-ui/pages/collection/storage-unit/list.tsx
packages/dina-ui/types/collection-api/resources/StorageUnit.ts

-Breadcrumb view.
-Storage List page.
-Tree view.

Added the storage type name in:

---

packages/common-ui/lib/bulk-data-editor/BulkDataEditor.tsx

-Changed the way "renderers" is imported from handsontable, which fixes the error.

Feedback 23553

---

packages/common-ui/lib/modal/modal.tsx
packages/dina-ui/components/object-store/metadata-bulk-editor/custom-default-values/DefaultValueConfigManager.tsx
packages/dina-ui/components/object-store/metadata-bulk-editor/custom-default-values/DefaultValueRuleEditor.tsx
packages/dina-ui/components/object-store/metadata-bulk-editor/custom-default-values/useDefaultValueRuleBuilderModal.tsx
packages/dina-ui/pages/object-store/upload.tsx

Multiple issues addressed
7 coding issues
1 issue confirmed by WCAG tab navigation test

Support 23615 WCAG issue updates

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collection/material-sample/workflows/split-run.tsx

-Added "Multiple" placeholder to "Set All" sample name.

Feedback 23679

---

packages/common-ui/lib/formik-connected/SelectFieldWithNav.tsx

Made the left/right buttons hidden when disabled.

Feedback 23680

---

packages/dina-ui/pages/collection/material-sample/workflows/split-run.tsx

Removed material sample description field.

Feedback 23681

---

packages/dina-ui/components/collection/DeterminationField.tsx

-Added open accordion view for multiple determinations in read-only mode.

Feedback 23596

---

packages/dina-ui/pages/seqdb/pcr-batch/edit.tsx
packages/dina-ui/types/seqdb-api/resources/PcrBatch.ts

Added the misssing fields to the PcrBatch for and view.

Feedback 23945

---

packages/common-ui/package.json
packages/dina-ui/components/collection/DeterminationField.tsx
packages/dina-ui/intl/dina-ui-en.ts
yarn.lock

Changed the determinations section to use accordions.

Feedback 24137

---

packages/dina-ui/components/collection/DeterminationField.tsx
packages/dina-ui/components/collection/useMaterialSample.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/page-tests/collection/workflow-template/__tests__/run.test.tsx

-Added test to add a Material Sample with determinations.

Feedback 24216

---

packages/common-ui/lib/index.ts
packages/common-ui/lib/util/useThrottledFetch.tsx
packages/common-ui/package.json
packages/dina-ui/components/collection/catalogue-of-life/CatalogueOfLifeNameField.tsx
packages/dina-ui/components/collection/catalogue-of-life/CatalogueOfLifeSearchBox.tsx
packages/dina-ui/components/collection/catalogue-of-life/ColDataSetDropdown.tsx
packages/dina-ui/components/collection/catalogue-of-life/__tests__/CatalogueOfLifeNameField.test.tsx
packages/dina-ui/components/collection/catalogue-of-life/dataset-search-types.ts
packages/dina-ui/components/collection/catalogue-of-life/name-search-types.ts
packages/dina-ui/components/collection/catalogue-of-life/nameusage-types.ts
packages/dina-ui/intl/dina-ui-en.ts
yarn.lock

Support 24112 co l plus integration part 2

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/page-tests/collection/collecting-event/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/workflow-template/__tests__/edit.test.tsx

Moved verbatim date to the top of the section.
Got rid of the toggle that hides the end time field.

Feedback 24282

---

packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesEditor.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collection/collecting-event/edit.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx
packages/dina-ui/pages/object-store/metadata/single-record-edit.tsx

-Removed the spacing from ManagedAttributesEditor.
-Added the footer to the pages using the ManagedAttributesEditor.
-Fixed the label for the Managed Attributes In Use selector.

Feedback 24306

---

packages/dina-ui/components/storage/StorageUnitChildrenViewer.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitChildrenViewer.test.tsx
packages/dina-ui/pages/collection/storage-unit/view.tsx
packages/dina-ui/types/collection-api/resources/StorageUnit.ts

Reverts AAFC-BICoE/dina-ui#492

Revert "Revert "Support 24314 storage unit detail view error""

---

packages/common-ui/lib/formik-connected/AutoSuggestTextField.tsx
packages/common-ui/lib/formik-connected/__tests__/AutoSuggestTextField.test.tsx
packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/DeterminationField.tsx
packages/dina-ui/components/collection/PreparationField.tsx
packages/dina-ui/types/collection-api/resources/CollectingEvent.ts

-Changed substrate field to be a string with autosuggest from other Collecting Event substrate values..
-Improved visuals on the autosuggest field, replaced debounce with useDebounce.

Feedback 24354

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/DeterminationField.tsx
packages/dina-ui/components/collection/PreparationField.tsx

Changed the auto suggest dropdowns to use the label for the user's locale.

Feedback 24311

---

packages/dina-ui/components/collection/useMaterialSample.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx

Added barcode field (Does not yet submit to the back-end)

Feedback 24407

---

packages/dina-ui/components/collection/SetDefaultSampleName.tsx
packages/dina-ui/components/collection/__tests__/SetDefaultSampleName.test.tsx
packages/dina-ui/components/collection/index.ts
packages/dina-ui/page-tests/collection/workflow-template/__tests__/run.test.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx

-Reverted the Identifiers section layout so the fieldshave their own labels.
-Added hidden SetDefaultSampleName component to auto-set the sample name prefix.

Feedback 24399

---

packages/common-ui/lib/formik-connected/MetersField.tsx

-Updated MetersField to make sure all conversion functions are using the same number of decimal places, which fixes the bug.

Feedback 24557

---

packages/common-ui/lib/formik-connected/AutoSuggestTextField.tsx
packages/common-ui/lib/formik-connected/DateField.tsx
packages/common-ui/lib/formik-connected/__tests__/AutoSuggestTextField.test.tsx
packages/dina-ui/components/collection/OrganismStateField.tsx
packages/dina-ui/components/collection/ScheduledActionsField.tsx
packages/dina-ui/components/collection/__tests__/ScheduledActionsField.test.tsx
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

-Added 'invalid' state to DateField.
-Made only actionType and date required.
-Made actionType and actionStatus autosuggest fields.

Fedback 24940

---

packages/dina-ui/components/collection/catalogue-of-life/CatalogueOfLifeSearchBox.tsx
packages/dina-ui/components/collection/catalogue-of-life/ColDataSetDropdown.tsx
packages/dina-ui/components/collection/catalogue-of-life/__tests__/CatalogueOfLifeNameField.test.tsx

Trimmed whitespace before sending to COL api.

Feedback 25165

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx

-Made the filter prop overridable in resource-select-fields.
-Added filter by group to the collection method dropdown.

Feedback 25236

---

packages/common-ui/common-ui-style.css
packages/common-ui/lib/index.ts
packages/common-ui/lib/intl/LanguageSelector.tsx
packages/common-ui/lib/table/__tests__/descriptionCell.test.tsx
packages/common-ui/lib/table/description-cell.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts
packages/dina-ui/pages/collection/collection-method/edit.tsx
packages/dina-ui/pages/collection/collection-method/list.tsx

https://redmine.biodiversity.agr.gc.ca/issues/25049

Support #25049 - View collection method description on list page

---

packages/dina-ui/components/collection/useMaterialSample.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

Added "isEmpty" check instead of falsey check.

Feedback 25268

---

packages/dina-ui/components/storage/BrowseStorageTree.tsx
packages/dina-ui/components/storage/__tests__/BrowseStorageTree.test.tsx

https://redmine.biodiversity.agr.gc.ca/issues/25369

Support #25369 - Sorting contents of a storage unit

---

packages/common-ui/lib/account/AccountProvider.tsx
packages/common-ui/lib/test-util/mock-app-context.tsx
packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/components/collection/catalogue-of-life/CatalogueOfLifeNameField.tsx
packages/dina-ui/components/collection/catalogue-of-life/CatalogueOfLifeSearchBox.tsx
packages/dina-ui/components/collection/catalogue-of-life/__tests__/CatalogueOfLifeNameField.test.tsx
packages/dina-ui/components/group-select/GroupSelectField.tsx
packages/dina-ui/components/group-select/__tests__/CollectionSelectField.test.tsx
packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx
packages/dina-ui/components/tag-editor/TagSelectField.tsx
packages/dina-ui/page-tests/dina-user/__test__/edit.test.tsx
packages/dina-ui/pages/_app.tsx
packages/dina-ui/pages/dina-user/edit.tsx
packages/dina-ui/pages/dina-user/view.tsx
packages/dina-ui/test-util/mock-app-context.tsx

Reverts AAFC-BICoE/dina-ui#577

Revert "Support 25319 as dina admin i should see the user menu"

---

packages/dina-ui/components/collection/MaterialSampleAssociationsField.tsx
packages/dina-ui/components/collection/VocabularySelectField.tsx
packages/dina-ui/components/collection/__tests__/VocabularySelectField.test.tsx
packages/dina-ui/components/index.ts

-Changed the vocab field to a select menu because free text isn't allowed.
-Updated VocabularySelectField so the correct localed labels are shown.

Feedback 25474

---

packages/common-ui/lib/formik-connected/FieldWrapper.tsx
packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/tag-editor/NotPubliclyReleasableWarning.tsx
packages/dina-ui/components/tag-editor/TagsAndRestrictionsSection.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/object-store/object/view.tsx

-Removed the preview and the "showing" text for spreadsheets.
-Fixed padding at top of object view page.

Feedback 25529

---

packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx
packages/dina-ui/components/search/useAutocompleteSearchButFallbackToRsqlApiSearch.ts
packages/dina-ui/components/search/useSearch.ts

Added the aliases to the person dropdown.

Feedback 25560

---

packages/common-ui/lib/table/date-cell.tsx
packages/dina-ui/components/object-store/exif-view/ExifView.tsx
packages/dina-ui/components/revisions/revision-row-configs/collectingevent-revision-row-config.tsx
packages/dina-ui/pages/collection/collecting-event/list.tsx
packages/dina-ui/pages/collection/collecting-event/revisions.tsx
packages/dina-ui/pages/collection/collecting-event/view.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/collection/preparation-type/view.tsx
packages/dina-ui/pages/collection/revisions-by-user.tsx
packages/dina-ui/types/collection-api/resources/MaterialSampleRunConfig.ts

-Added VIew Details button to collecting event list page rows.
-Added the material sample list to the Collecting event view page.

Feedback 25657

---

packages/dina-ui/components/collection/collecting-event/useCollectingEvent.tsx
packages/dina-ui/page-tests/collection/collecting-event/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/page-tests/collection/workflow-template/__tests__/run.test.tsx
packages/dina-ui/types/collection-api/resources/CollectingEvent.ts

Made the coord systemj null for new collecting events with no coordinates set.

Feedback 25681

---

packages/dina-ui/pages/collection/managed-attribute/edit.tsx
packages/dina-ui/pages/collection/managed-attribute/list.tsx
packages/dina-ui/types/collection-api/resources/ManagedAttribute.ts

-Added multilingual desription to collection module's managed attribute.

Feedback 25782

---

packages/common-ui/lib/list-page-layout/ListPageLayout.tsx
packages/dina-ui/pages/object-store/object/list.tsx

-Added the caption column to the stored objects table.

Feedback 26084

---

packages/common-ui/lib/formik-connected/ToggleField.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/BulkEditTabWarning.test.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/bulk-edit-tab.test.tsx
packages/dina-ui/components/collection/collecting-event/DeterminationField.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleFormNav.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx

Removed the isPrimary/isFileAs auto-set.

In progress 26281

---

packages/dina-ui/components/collection/collecting-event/CollectingEventLinker.tsx
packages/dina-ui/pages/collection/collecting-event/list.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx

Added collection numbers to Collecting event loist page and the linker table in Material Sample edit page.

Feedback 26282

---

packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/collection/material-sample/ScheduledActionsField.tsx
packages/dina-ui/components/collection/material-sample/__tests__/ScheduledActionsField.test.tsx
packages/dina-ui/components/collection/material-sample/useMaterialSample.tsx
packages/dina-ui/page-tests/collection/workflow-template/__tests__/run.test.tsx

-Made sure the 'scheduledAction' (singular) field from the template is  not persisted.
-Improved the workflow run test so it does the submission and checks the values.

Feedback 26308

---

packages/dina-ui/components/collection/collecting-event/DeterminationField.tsx
packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesEditor.tsx
packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesViewer.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/types/collection-api/resources/Determination.ts
packages/dina-ui/types/collection-api/resources/ManagedAttribute.ts

-Added determination option in managed attribute form.
-Added managed attribute section to DeterminationField.
-Added read-only mode view for ManagedAttributesEditor component.

Feedback 26312

---

packages/dina-ui/components/object-store/metadata/MetadataDetails.tsx
packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/object-store/metadata/__tests__/MetadataPreview.test.tsx
packages/dina-ui/page-tests/object-store/object/__tests__/view.test.tsx

-Changed the query for the Object Upload so it fetches the Object Upload by ID instead of filtering by fileIdentifier.
-Updated tests to make sure exif data renders.

Feedback 26388

---

packages/dina-ui/components/storage/StorageUnitForm.tsx
packages/dina-ui/intl/dina-ui-en.ts

Feedback 26448

---

packages/dina-ui/pages/collection/managed-attributes-view/edit.tsx

Reverse "Delete" and "Move" icons in Custom Views

reverse delete and move icons in managed-attributes-view/edit

---

packages/dina-ui/components/storage/AssignedStorage.tsx
packages/dina-ui/components/storage/StorageSearchSelector.tsx
packages/dina-ui/components/storage/StorageUnitBreadCrumb.tsx

https://github.com/AAFC-BICoE/dina-ui/commit/af8535cc5e617bfb019772b6f4842ad174d9a273

storage link opens in new tab from material sample edit

---

packages/common-ui/lib/api-client/useQuery.tsx
packages/dina-ui/components/bulk-material-sample/bulk-edit-tab.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleBreadCrumb.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/collection/material-sample/material-sample-form-nav/MaterialSampleFormNav.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/package.json
packages/dina-ui/pages/collection/material-sample/view.tsx

Highest parent:
First gen child:
Second gen child:

26988 show inherited collecting event

---

packages/dina-ui/components/bulk-material-sample/__tests__/BulkEditTabWarning.test.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/collection/collecting-event/DeterminationField.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts
packages/dina-ui/types/collection-api/resources/Determination.ts

https://redmine.biodiversity.agr.gc.ca/issues/27154

Support #27154 - Fixed typo in determination is filed as

---

packages/common-ui/lib/query-page/QueryPage.tsx
packages/common-ui/lib/query-page/__test__/QueryPage.test.tsx
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/table/date-cell.tsx
packages/common-ui/lib/table/stringArray-cell.tsx
packages/common-ui/lib/util/__tests__/transformToDSL.test.ts
packages/common-ui/lib/util/transformToDSL.ts
packages/dina-ui/components/collection/material-sample/__tests__/MaterialSampleForm.test.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/object-store/object/list.tsx

https://redmine.biodiversity.agr.gc.ca/issues/26976

Support #26976 - Fix search sorting

---

packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/pages/object-store/image-viewer.tsx

https://redmine.biodiversity.agr.gc.ca/issues/27202

27202_object_store_split_function_issue

---

packages/common-ui/lib/query-page/QueryPage.tsx
packages/common-ui/lib/query-page/__test__/QueryPage.test.tsx

https://redmine.biodiversity.agr.gc.ca/issues/27262

Support #27262 - Fix count round 2

---

package.json
yarn.lock

https://redmine.biodiversity.agr.gc.ca/issues/27231

Support #27231 - Update minimist

---

packages/common-ui/lib/table/date-cell.tsx
packages/common-ui/lib/table/stringArray-cell.tsx
packages/common-ui/lib/util/__tests__/transformToDSL.test.ts
packages/common-ui/lib/util/transformToDSL.ts
packages/dina-ui/pages/collection/material-sample/list.tsx

https://redmine.biodiversity.agr.gc.ca/issues/27402

Support #27402 - Sorting broken on some columns

---

packages/dina-ui/components/object-store/file-upload/FileUploadProvider.tsx
packages/dina-ui/page-tests/object-store/__tests__/upload.test.tsx

https://redmine.biodiversity.agr.gc.ca/issues/27410

Support #27410 - Object store large upload timeout

---

packages/common-ui/lib/tooltip/Tooltip.tsx
packages/dina-ui/components/collection/material-sample/PreparationField.tsx
packages/dina-ui/intl/dina-ui-en.ts

Added tooltips and fixed some tooltip issues.

Support #27394 - Improve preparation section documentation

---

packages/common-ui/lib/formik-connected/AutoSuggestTextField.tsx
packages/common-ui/lib/formik-connected/__tests__/AutoSuggestTextField.test.tsx
packages/dina-ui/pages/loan-transaction/transaction/edit.tsx

https://redmine.biodiversity.agr.gc.ca/issues/27210

Support #27210 - Transaction page is sending invalid request on load

---

packages/common-ui/lib/index.ts
packages/common-ui/lib/table/BooleanCell.tsx
packages/common-ui/lib/table/__tests__/BooleanCell.test.tsx
packages/dina-ui/pages/loan-transaction/transaction/list.tsx

https://redmine.biodiversity.agr.gc.ca/issues/27183

Support #27183 - Add search to transaction

---

package.json
packages/common-ui/package.json
packages/dina-ui/package.json
packages/dina-ui/page-tests/object-store/object-subtype/list.test.tsx
yarn.lock

https://redmine.biodiversity.agr.gc.ca/issues/27478

Support #27478 - Update dependencies

---

packages/common-ui/lib/formik-connected/FieldExtensionSelectField.tsx
packages/common-ui/lib/formik-connected/ToggleField.tsx
packages/common-ui/lib/formik-connected/__tests__/FieldExtensionSelectField.test.tsx

- Restrictions now have a None option
- Fixed Toggle button toggling when clicking anywhere in the label space

Support 27596 Restrictions section issues

---

packages/common-ui/lib/tooltip/Tooltip.tsx
packages/dina-ui/components/collection/material-sample/PreparationField.tsx

- Tooltip links now open in new tab
- Prep type links direct to DINA User Guide

Support 27591 - Tooltips small fixes

---

packages/dina-ui/components/collection/AssociationsField.tsx
packages/dina-ui/components/collection/AssociationsHostField.tsx
packages/dina-ui/components/collection/global-names/GlobalNamesSearchBox.tsx

- Associations search box changed from Catalogue of Life to Global Names

27641_change_associations_host_organism_search

---

packages/common-ui/lib/text-field-with-multiplication-button/TextFieldWithMultiplicationButton.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/collecting-event/GeoReferenceAssertionRow.tsx
packages/dina-ui/components/collection/material-sample/PreparationField.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Added tooltips for Collecting Event Host
- Added tooltips for Collecting Event Collection Method
- Added tooltips for Collecting Event Substrate
- Added tooltips for Georeferencing Coordinate Uncertainty In Meters
- Added tooltips for Determinations Verbatim Scientific Name "x" button

27642 Add some missing tooltips

---

packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx
packages/dina-ui/components/search/useAutocompleteSearchButFallbackToRsqlApiSearch.ts
packages/dina-ui/components/search/useSearch.ts

- Added documentId query param to search-ws/auto-complete to get person id
- No longer throws error when adding person by text searching

27956 Error creating collecting event with collector

---

packages/common-ui/lib/resource-select/ResourceSelect.tsx
packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx

- Fixed bug where multiple undefined collectors were added to ResourceSeclectField

27944 Duplicated collectors issue collecting event

---

packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Added Collection Number field, takes fieldNumber from collection-api

28042 Add API field fieldNumber

---

packages/dina-ui/components/bulk-edit/BulkEditNavigator.tsx
packages/dina-ui/components/bulk-material-sample/MaterialSampleBulkEditor.tsx

- Refactored funtion to get tab name out of BulkEditNavigator

28342 move tab names from useBulkEdit definitions

---

packages/common-ui/lib/util/transformToDSL.ts
packages/dina-ui/components/project/ProjectFormLayout.tsx
packages/dina-ui/pages/collection/assemblage/edit.tsx

- Added uuid type to transformToDSL
- Changed Project/Assemblage custom queries to use new uuid type
- Removed group from custom queries and made it optional in TransformQueryToDSL

28701 improvements for QueryPage viewMode

---

packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/components/collection/SaveAndCopyToNextSuccessAlert.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/identifier/IdentifierRow.tsx
packages/dina-ui/components/object-store/attachment-list/ExistingAttachmentsTable.tsx
packages/dina-ui/components/object-store/attachment-list/ExistingObjectsAttacher.tsx
packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/components/project/ProjectFormLayout.tsx
packages/dina-ui/components/seqdb/sanger-workflow/SangerSampleSelectionStep.tsx
packages/dina-ui/components/table/thumbnail-cell.tsx
packages/dina-ui/pages/collection/assemblage/edit.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/index.tsx
packages/dina-ui/pages/managed-attribute/list.tsx
packages/dina-ui/pages/object-store/object/list.tsx

- refactored Navbar to use next.js Link component with passHref param
- refactored links everywhere in the project from using the <a> anchor to wrapping in Link with passHref

28607 Improve links to use NextJS links

---

packages/dina-ui/components/collection/GeoReferenceAssertionField.tsx
packages/dina-ui/pages/collection/form-template/edit.tsx
packages/dina-ui/types/collection-api/resources/MaterialSampleForm.ts

- Checking include all checkbox in georeference should toggle all the checkboxes in the georeference section

28753 Georeference include all checkbox not working

---

packages/dina-ui/components/form-template/formTemplateUtils.ts
packages/dina-ui/pages/collection/form-template/edit.tsx
packages/dina-ui/types/collection-api/resources/form-legends/MaterialSampleForm.ts

- Editing checkboxes now correctly saves new state

28756 Editing Form Template not saving

---

package.json
packages/dina-ui/package.json
yarn.lock

- Upgrade moment to version 2.29.4
- Upgrade node-fetch, resolve to 2.6.7
- Upgrade minimatch, resolve to 3.1.2

29020 Update dependencies

---

packages/dina-ui/components/collection/form-template/useMaterialSampleFormTemplateSelectState.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx

- Form Template now applies nav order

29007 Form Template should apply nav order

---

packages/dina-ui/components/collection/TabbedResourceLinker.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx

- Form Template now hides Attach Existing tab for CE and AE
- Using Form Template now hides Attach Existing tab

29148 Remove attach existing tab for form template

---

packages/dina-ui/page-tests/seqdb/pcr-batch/__tests__/edit.test.tsx

- Added two tests for the storage unit.

Support #29143 - Add test coverage for PcrBatch Storage Unit Type

---

packages/dina-ui/pages/object-store/object/view.tsx

- Object store view now shows attached Material Samples

29137 Show material sample from object store

---

packages/dina-ui/page-tests/loan-transaction/transaction/__tests__/edit.test.tsx
packages/dina-ui/pages/loan-transaction/transaction/edit.tsx

- Transaction can now remove attached Material Sample

29279 Transaction cannot remove attached Material Sample

---

packages/common-ui/lib/formik-connected/FieldWrapper.tsx

- Managed attributes fields now correctly shows up in form template

29357 Managed attributes not working form template

---

packages/common-ui/lib/formik-connected/GroupedCheckBoxFields.tsx
packages/common-ui/lib/formik-connected/PlaceSectionsSelectionField.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/collecting-event/useCollectingEvent.tsx

- Added logic to disable checkboxes if osm type and osm id not available
- Fixed enable all checkboxes logic to exclude disabled boxes

29426 Can't save Neatby Building in Geographic Place

---

packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/storage/StorageUnitBreadCrumb.tsx
packages/dina-ui/components/storage/__tests__/AssignedStorage.test.tsx
packages/dina-ui/components/storage/__tests__/BrowseStorageTree.test.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitBreadCrumb.test.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitChildrenViewer.test.tsx
packages/dina-ui/page-tests/collection/storage-unit/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/storage-unit/list.tsx

Reverts AAFC-BICoE/dina-ui#891

Revert "Support #29358 storage unit display remove type"

---

package.json
yarn.lock

- Resolve loader-utils to 1.4.2
- Resolve json5 to 2.2.2

29692 UI dependencies update

---

packages/common-ui/lib/list-page/QueryPage.tsx

- QueryPage save selected groups when navigating between pages
- Implemented local storage to store selected groups

29859 Group selection lost when back is pressed

---

packages/dina-ui/components/collection/form-template/MaterialSampleFormTemplateSelect.tsx

- Removed the group filtering on the dropdown.

Bug #29890 - Form template dropdown permission issues

---

.prettierrc

- Added the basic prettier configuration. Should be what was being used before without adding trailing commas anymore.

Support #29904 - Fix prettier configuration for project

---

packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/object-store/managed-attributes/ManagedAttributesEditor.tsx

- User can no longer remove managed attribute from dropdown

29886 Improve managed attribute usage view

---

packages/common-ui/package.json
yarn.lock

Support #29684 - Update keycloak JS

---

packages/dina-ui/components/storage/StorageUnitForm.tsx
packages/dina-ui/pages/collection/storage-unit/list.tsx
packages/dina-ui/types/collection-api/resources/StorageUnit.ts

- Add Barcode Textfield to Storage Unit edit and view

29902 Add barcode field to storage unit

---

packages/dina-ui/page-tests/collection/form-template/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/form-template/edit.tsx

- Fixed bug where using a Form Template with Collecting Event in Material Sample threw access denied error

29991 Form Template Collecting Event Access Denied

---

packages/dina-ui/components/workbook/WorkbookColumnMapping.tsx
packages/dina-ui/components/workbook/utils/workbookMappingUtils.ts

- Workbook data validation now uses correct rowNumber in error messages

30084 Workbook error row number not correct

---

packages/common-ui/lib/tooltip/Tooltip.tsx
packages/dina-ui/components/object-store/managed-attributes/ManagedAttributeField.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Added tooltips to managed attributes to display attribute description

30338 Display Managed Attribute description on tooltips

---

packages/common-ui/lib/formik-connected/__tests__/DataEntry.test.tsx
packages/dina-ui/components/collection/useVocabularyOptions.ts
packages/dina-ui/types/collection-api/resources/Protocol.ts
packages/dina-ui/types/collection-api/resources/VocabularyElement.ts

Change to use the key, other than term

30499 update protocolView to use key

---

packages/dina-ui/components/storage/StorageFilter.tsx
packages/dina-ui/components/storage/StorageUnitChildrenViewer.tsx
packages/dina-ui/components/storage/StorageUnitForm.tsx

Swap storage unit name and unit type.

30509 improve storage display

---

packages/common-ui/lib/formik-connected/data-entry/DataBlock.tsx
packages/common-ui/lib/formik-connected/data-entry/DataEntry.tsx
packages/common-ui/lib/formik-connected/data-entry/DataRow.tsx

- Added tooltips for Field Extensions that has description

30535 Show tooltips with description on Field Extension

---

packages/dina-ui/pages/seqdb/pcr-batch/edit.tsx

- Renamed Thermocycler to Thermocycler Unit

30680 Rename PCR Batch Thermocycler field

---

packages/common-ui/lib/list-page/query-builder/query-builder-value-types/QueryBuilderManagedAttributeSearch.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/QueryBuilderManagedAttributeSearch.test.tsx

- Switched to using a ResourceSelect for Managed Attribute selection. Which also adds debounce support which is nice.
- Updated the test to show the new state.

Bug #30807 - Issue with managed attribute search

---

packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/collection/material-sample/list6.tsx

- Removed view edit delete quick links column from material sample list page

30815 Remove material sample list view quick links

---

packages/dina-ui/components/object-store/attachment-list/ExistingAttachmentsTable.tsx
packages/dina-ui/components/object-store/attachment-list/ExistingObjectsAttacher.tsx
packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/object-store/stored-object-gallery/StoredObjectGallery.tsx
packages/dina-ui/components/table/__tests__/thumbnail-cell.test.tsx
packages/dina-ui/components/table/thumbnail-cell.tsx
packages/dina-ui/pages/object-store/object/list.tsx

- Changed thumbnail image endpoint to use regular /derivative endpoint
- Added necessary accessors to get derivative information
- Fixed tests

30830 Load thumbnails using regular file endpoint

---

packages/dina-ui/components/seqdb/pcr-workflow/PcrReactionTable.tsx
packages/dina-ui/components/seqdb/pcr-workflow/SangerPcrReactionStep.tsx
packages/dina-ui/pages/seqdb/pcr-workflow/run.tsx

- Fixed PCR Reaction Results tab to display dropdowns in Result column when in edit mode

31094 PCR Workflow PCR Reaction Results not working

---

.vscode/settings.json
packages/dina-ui/pages/collection/extension/list.tsx

- Removed keys column
- Added Unit column that displays unit if available

31160 Display units on field extension page

---

packages/common-ui/lib/formik-connected/data-entry/DataBlock.tsx
packages/common-ui/lib/formik-connected/data-entry/DataRow.tsx

- Added Unit column to field extension for Material Sample and Collecting Event

31233 Add unit to field extension usage

---

packages/dina-ui/components/button-bar/nav/nav.css

- Fixed dropdown menu z-index to stay on top

31439 Dropdown menu appears behind Data Components

---

packages/common-ui/lib/custom-query-view/CustomQueryPageView.tsx

- Added label to dropdown to meet Axe Accessibility WCAG 2.1 requirements

31560 WCAG Pre-QA Fixes

---

packages/dina-ui/components/collection/material-sample/GenerateLabelDropdownButton.tsx

- Changed report-request post payload according to new template
- Changed download file's name to be more useful

31556 Adapt GenerateLabelDropdown tot handle new template

---

packages/common-ui/lib/table8/date-cell8.tsx

- Fixed Material Sample Created On Sorting

31415 Material Sample Created On Sorting not working

---

packages/dina-ui/components/object-store/metadata/useMetadataThumbnailPath.tsx
packages/dina-ui/components/object-store/stored-object-gallery/StoredObjectGallery.tsx
packages/dina-ui/components/table/thumbnail-cell.tsx

- Refactored logic to get thumbnail in thumbnail-cell into it's own hook
- Reused new hook for StoreObjectGallery to get thumbnail correct
- Single point of code control

31770 Object store gallery view not showing thumbnail

---

packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/collection/material-sample/PreparationField.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

Note, that the search does not search in the preparation managed attributes and form templates are not working

Added preparations managed attributes

---

packages/dina-ui/components/collection/global-names/GlobalNamesField.tsx

- Show More anchor in Organisms determination show now be interactable using tab

Fix Focus Order

---

packages/common-ui/lib/tooltip/Tooltip.tsx
packages/dina-ui/components/collection/material-sample/GenerateLabelDropdownButton.tsx
packages/dina-ui/components/managed-attributes/ManagedAttributeField.tsx

- Changed tooltip alt to fall back on directText
- Changed tooltip alt to fall back on attribute name
- Added aria label to generate label button

31709 WCAG Material Sample View Revisions Non text content

---

packages/dina-ui/components/object-store/metadata/MetadataDetails.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Added file size row in binary base conversion in object store view page

31776 Show file size under File Storage object store

---

packages/dina-ui/components/button-bar/nav/nav.tsx

- Added menubar role to navbar
- Added menuitem role to dropdown items

31715 WCAG material sample view revisions role

---

packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/components/object-store/metadata/__tests__/MetadataFileView.test.tsx
packages/dina-ui/types/objectstore-api/resources/ObjectUpload.ts

- Disable query if resource does not fall into a file type supported for showing

31887 object store details view loading objects

---

packages/common-ui/lib/table/Pagination.tsx
packages/common-ui/lib/table/react-table.css

- Made CSS change to make focus around rows page page dropdown visible in Chrome

31912 WCAG Material Sample View Revisions Focus Visible

---

packages/common-ui/lib/util/isBlankResourceAttribute.ts

- Removing Digitized By in metadata bulk edit should now remove the relationship

31941 Edit all not removing relationships

---

packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport8.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/__snapshots__/QueryBuilderElasticSearchExport.test.tsx.snap

- Source array now inside of "includes".
- Updated snapshot to reflect the change.

Support #31953 - Filters update _source sent to elastic search

---

packages/common-ui/lib/column-chooser/ColumnChooser.tsx
packages/common-ui/lib/column-chooser/GroupedCheckboxWithLabel.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/dina-ui/components/table/thumbnail-cell.tsx
packages/dina-ui/page-tests/object-store/object/__tests__/view.test.tsx
packages/dina-ui/pages/collection/material-sample/export.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/object-store/object/list.tsx

- Added Select Columns dropdown to QueryPage component - all list pages that uses QueryPage for elastic search will have Select Columns
- Refactored export page to work with ColumnChooser changes
- Added local storage for each view page
- Squashed bugs

30839 Allow to customize search columns

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collection/form-template/list.tsx

- Added Split Configuration boolean column to denote whether a form template has a split config
- Renamed Create Sample With Form Template button to Create Sample

31764 Improve FormTemplate list page

---

package.json
packages/common-ui/lib/account/__tests__/AuthenticatedApiClientProvider.test.tsx
packages/common-ui/lib/collapser/__tests__/useCollapser.test.tsx
packages/common-ui/lib/loading-spinner/__tests__/LoadingSpinner.test.tsx
yarn.lock

Added new dependencies.  Need to run yarn to install them.

31993 introduce react testing library

---

packages/common-ui/lib/list-page/__tests__/__snapshots__/UseIndexMapping.test.tsx.snap
packages/common-ui/lib/list-page/useIndexMapping.tsx

- Fixed bug where selecting AC Metadata Creator in dropdown also selected DC Creator
- Changed Display Name to Uploaded By and Digitized by for acMetadataCreator and dcCreator, respectively

31926 Improve consistency of object store labels

---

packages/common-ui/lib/formik-connected/ToggleField.tsx
packages/dina-ui/components/tag-editor/TagsAndRestrictionsSection.tsx

- Changed Not Publicly Releasable toggle to false on Metadata creation
- This is consistent with Material Sample and Collecting Event

32010 Object store saving incorrect publicly releasable on creation

---

packages/common-ui/lib/list-page-layout/bulk-buttons.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport.tsx

- User can now select resource rows to be exported
- If no rows are selected, everything is exported taking into account the user input query
- Total matched records reflects number of rows selected by user if any

32087 List page selection should apply for exporting

---

packages/common-ui/lib/table/react-table.css

- Changed table sorting indicator to arrows

28727 Change table sorting indicator to arrows

---

packages/dina-ui/components/managed-attributes/ManagedAttributeField.tsx

- Tooltip besides managed attribute's name now displays unit if available

32147 Display unit on managed attributes usage tooltips

---

packages/dina-ui/components/managed-attributes/ManagedAttributesViewer.tsx

- Changed DinaForm to DinaFormSection in ManagedAttributesViewer to override initialValues
- Changed initial values from array to object, this is where the problem was
- Override managedAttributes values with sorted values
- Changed FieldView name to get the correct managed attributes key

32162 Object store managed attribute labels not attached to correct data

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts

- Add French translation for Material Sample Field Extensions
- Add French translation for Collecting Event Field Extensions

32017 Add all filter options to column selection

---

packages/dina-ui/components/button-bar/nav/nav.css
packages/dina-ui/components/button-bar/nav/nav.tsx

- Fixed menubar, menu, menuitem hierarchy following WAI ARIA best practices

32208 WCAG Round 3 1.3.1 Info and Relationships

---

packages/dina-ui/components/object-store/metadata/MetadataFileView.tsx
packages/dina-ui/components/object-store/metadata/useMetadataThumbnailPath.tsx
packages/dina-ui/components/table/thumbnail-cell.tsx

- Added more descriptive alt text for object store images

32207 WCAG Round 3 1.1.1 Non-text content

---

packages/dina-ui/components/collection/material-sample/OrganismStateField.tsx

- Fixed organism remarks TextField, now correctly saves remarks attribute

322666 Can't save organism remarks

---

packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/list-page/query-builder/QueryBuilder.tsx
packages/common-ui/lib/list-page/reload-last-search/useLastSavedSearch.tsx
packages/common-ui/lib/list-page/saved-searches/SavedSearch.tsx

- QueryBuilder now loads localStorage saved queries

32342 Fix QueryBuilder not loading searches

---

packages/dina-ui/pages/collection/extension/list.tsx

Please review and merge this one first https://github.com/AAFC-BICoE/dina-ui/pull/1178

32205 free text search on field extension page

---

packages/common-ui/lib/column-selector/ColumnSelectorUtils.tsx
packages/common-ui/lib/list-page/__tests__/UseElasticSearchDistinctTerm.test.tsx
packages/common-ui/lib/list-page/useElasticSearchDistinctTerm.tsx

- Aggregation type are now included with the responses. Fixed it for both attribute and nested level aggregations.

Bug #32603 - Autocomplete on the query builder error

---

packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/QueryBuilderElasticSearchExport.test.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/__snapshots__/QueryBuilderElasticSearchExport.test.tsx.snap

- Implemented a fallback for sorting to fallback on accessorKey when id is not available in column definition
- Added test case

32634 Sort broken on list page

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx

- Export page no longer has Apply button
- Export page should now correct export checked items without need for Apply button

32605 Export not working with columns selection

---

packages/common-ui/lib/intl/LanguageSelector.tsx

- Default language to en if support-languages-iso not available

32664 Gracefully  handle no language environment variables

---

packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/__snapshots__/QueryBuilderElasticSearchExport.test.tsx.snap

- Multi sorting now creates a sort field with array instead  of object
- Update snapshot tests

32636 Issue with multi sort on table

---

packages/common-ui/lib/date/DateView.tsx

- Refactored DateView.tsx to use Intl.DateTimeFormat

32637 Use DateTimeFormat to convert dates

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx

- Select Column menu now only appears when user clicks on button instead of hover

32887 Make Select Column button menu appear only on click

---

packages/common-ui/lib/index.ts
packages/common-ui/lib/list-page-layout/DataExportListPageLayout.tsx
packages/dina-ui/pages/data-export/list.tsx
packages/dina-ui/pages/dina-user/view.tsx

- Refactored data export list logic from existing data-export list page to DataExportListPageLayout component
- DataExportListPageLayout should already follow the requirements for the ticket
- Add DataExportListPageLayout component to dina-user/view page under Data Exports section

32886 Add new export list page

---

packages/dina-ui/pages/data-export/export.tsx

- Object Export should not export large image

33010 Object Export not exporting large image

---

jest.config.ts
package.json
packages/common-ui/lib/api-client/ApiClientContext.tsx
packages/common-ui/lib/api-client/__tests__/ApiClientContext.test.ts
yarn.lock

- Resolve @babel/traverse to 7.23.2

32935 update dependencies

---

Dockerfile

32076 Update Caddy

---

packages/common-ui/lib/account/NavBarUserControl.tsx
packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/common-ui/lib/list-page-layout/DataExportListPageLayout.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/dina-ui/pages/dina-user/view.tsx

- Fixed bug where Export page throws error if unchecking default columns
- Removed back to list page link
- Added Export Type column

32987 Improve user page

---

packages/dina-ui/components/collection/collecting-event/useCollectingEvent.tsx

- Fix duplicate attachments and collectors in collectingEventQuery response

33152 Error when saving Material Sample with Collecting Event

---

packages/dina-ui/pages/data-export/export.tsx

- Refactored Export download logic with async status checking from exportData into function
- Re-use function for exportObject
- Exporting and downloading object should now be more stable with status checking

33212 Improve stability of Object Export options

---

packages/common-ui/lib/formik-connected/FieldWrapper.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

- Added conditional check on visibleManagedAttributes in FieldWrapper to prevent null field error
- Added visibleManagedAttributesKeys to components on the view page to correctly show/hide managed attributes according to Form Template

33256 Error message when using Form Templates on Material Sample View

---

packages/common-ui/lib/column-selector/ColumnSelectorUtils.tsx
packages/dina-ui/types/collection-api/resources/ManagedAttribute.ts

- Add isKeyword true to managed attribute columns
- ES request for managed attributes now containers .keyword, no longer failing

33274 Can't sort on managed attribute on object store list view

---

packages/common-ui/lib/column-selector/ColumnSelectorUtils.tsx

- Fix managed attribute columns name from managedAttribute.key to managedAttributes.key

33278 Export view not sending the right columns names

---

packages/dina-ui/components/collection/material-sample/GenerateLabelDropdownButton.tsx
packages/dina-ui/components/page-layouts/ViewPageLayout.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx
packages/dina-ui/pages/collection/storage-unit/view.tsx

- Refactored GenerateLabelDropdownButton to handle any type of resource
- Added GenerateLabelDropdownButton to ViewPageLayout button bar
- Added enabled GenerateLabelDropdownButton in storage unit view

32469 Add print barcode buttom to Storage Unit view

---

packages/dina-ui/pages/index.tsx

This was supposed to be included with the last PR #1288

Add report template upload option to homepage

---

packages/dina-ui/pages/workbook/upload.tsx

- Changed all instances of objectstore-api/conversion/workbook to objectstore-api/workbook/conversion to match changes in objectstore-api

33559 Change workbook conversion url

---

packages/dina-ui/pages/export/data-export/export.tsx

33794 View Export History button fix

---

packages/common-ui/lib/formik-connected/__tests__/DataEntry.test.tsx
packages/dina-ui/components/bulk-edit/__tests__/BulkEditTabWarning.test.tsx
packages/dina-ui/components/bulk-edit/__tests__/useBulkEditTab.test.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/collection/MaterialSampleAssociationsField.tsx
packages/dina-ui/components/collection/__tests__/VocabularySelectField.test.tsx
packages/dina-ui/components/collection/classification/ClassificationField.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/collecting-event/DeterminationField.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleInfoSection.tsx
packages/dina-ui/components/collection/material-sample/PreparationField.tsx
packages/dina-ui/components/collection/material-sample/SplitConfigurationSection.tsx
packages/dina-ui/components/collection/material-sample/__tests__/MaterialSampleForm.test.tsx
packages/dina-ui/components/collection/protocol/ProtocolDataField.tsx
packages/dina-ui/components/collection/protocol/ProtocolForm.tsx
packages/dina-ui/components/seqdb/seq-worksheet/SeqProtocolReactionTable.tsx
packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx
packages/dina-ui/components/workbook/utils/FieldMappingConfig.ts
packages/dina-ui/components/workbook/utils/__tests__/workbookMappingUtils.test.ts
packages/dina-ui/page-tests/collection/collecting-event/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/form-template/__tests__/edit.test.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/bulk-create.test.tsx
packages/dina-ui/page-tests/collection/protocol/__test__/edit.test.tsx
packages/dina-ui/pages/collection/protocol/list.tsx

- Replaced collection-api/vocabulary with collection-api/vocabulary2

33770 Replace all vocabulary endpoints

---

packages/dina-ui/pages/export/report-template/edit.tsx

- Eliminate report-template query when adding new template

33792 Report Template invalid request

---

packages/common-ui/lib/list-page-layout/DataExportListPageLayout.tsx
packages/common-ui/lib/list-page-layout/ListPageLayout.tsx

- Added Bulk delete button to data-export/list page
- Fixed grouped check box id so that selecting a checkbox now enables the delete selected button

33816 Add Delete exports button

---

packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx

Please review and merge https://github.com/AAFC-BICoE/dina-ui/pull/1300 first

33805 move collecting event managed attributes in existing section

---

packages/dina-ui/pages/dina-user/view.tsx

- dina-user/view Data Exports table should now display downloads for the viewed user instead of current user

33837 User view display downloads fix

---

packages/dina-ui/components/workbook/WorkbookDisplay.tsx

- Fix table column headers to fit to content, now has horizontal scroll bar

33927 Workbook Upload fix table display

---

packages/common-ui/lib/list-page-layout/bulk-buttons.tsx
packages/dina-ui/pages/export/data-export/export.tsx

- Change export to use session storage instead of local storage
- Should now be able to export object with multiple DINA tabs open

33908 Fix object export radio button disabled

---

packages/dina-ui/components/collection/material-sample/useMaterialSampleRelationshipColumns.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

- Material Sample Children table now greys out children material samples that has materialSampleState

34028 Grey out material sample children

---

packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx
packages/dina-ui/components/workbook/utils/workbookMappingUtils.ts

- The problem was that the apostrophe in libreoffice is actually a different character, it's actually a 'right single quotation mark' instead of an 'apostrophe'
- Added a regex to replace all right single quotation marks with apostrophe
- Should now correctly link fields with right single quotation marks in libreoffice to fields with apostrophes in DINA

34029 Workbook auto linking apostrophe issue

---

packages/common-ui/lib/list-page/QueryPage.tsx

- Added missing dependency to useMemo for the search result to re-render the checkboxes.

Support #34086 - Select all malfunctioning

---

packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/components/object-store/file-view/__tests__/FileView.test.tsx

- Fixed rendering behavior for .docx file type to be consistent with .doc

34062 word document rendering broken

---

packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/index.tsx

- Added new menu to homepage and nav bar.
- Moved Form Templates to this new section.
- Added a user profile link which links to the currently logged in users profile page.

Support #34600 - Add new menu configuration

---

package.json
packages/dina-ui/components/bulk-edit/__tests__/useBulkEditTab.test.tsx
packages/dina-ui/components/bulk-material-sample/MaterialSampleBulkEditor.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/collection/TabbedResourceLinker.tsx
packages/dina-ui/components/collection/material-sample/__tests__/MaterialSampleForm.test.tsx
packages/dina-ui/components/collection/material-sample/useMaterialSample.tsx

- Bulk creating material samples and attaching collecting events should now create individual collecting events per sample

34475 Bulk creating material samples collecting events issues

---

packages/dina-ui/components/collection/material-sample/OtherIdentifiersSection.tsx

- Fixed issue with identifier type displaying the value instead of label. Tested in english and french.

Support #34728 - Other identifier type dropdown should display titles

---

packages/common-ui/lib/resource-select/ResourceSelect.tsx

- ResourceSelect will sort alphabetically the results now.

Support #34426 - Change managed attribute order query builder

---

packages/dina-ui/components/seqdb/container-grid/DraggableItemBox.tsx

- Added primer name to the material sample in the coordinate selector.

Support #34832 - Sequence Batch layout missing primer name

---

packages/dina-ui/components/seqdb/pcr-workflow/PcrReactionTable.tsx
packages/dina-ui/components/seqdb/pcr-workflow/SangerPcrReactionStep.tsx
packages/dina-ui/components/seqdb/pcr-workflow/pcr-batch-plating-step/SangerPcrBatchItemGridStep.tsx

- Move Worksheet from "Select Coordinates" tab to "PCR Reaction Results" tab

34833 Move PCR Worksheet button to next tab

---

packages/dina-ui/components/seqdb/container-grid/ContainerGrid.tsx
packages/dina-ui/components/seqdb/container-grid/DraggableItemBox.tsx
packages/dina-ui/components/storage/StorageUnitGrid.tsx

- Sample name in storage grid is now hyper link to material sample

34821 Sample name in storage grid hyper link

---

packages/dina-ui/components/seqdb/seq-worksheet/SeqProtocolReactionTable.tsx
packages/dina-ui/pages/seqdb/pcr-workflow/worksheet.tsx

- Added experimenters to the include field for the pcr-batch query
- worksheet should now correct display Experimenters

34851 PCR worksheet not displaying PCR Protocol data

---

Dockerfile

- Updated Caddy version to 2.6.4

34264 Update caddy to 2.6.4

---

packages/common-ui/lib/formik-connected/DateField.tsx
packages/common-ui/lib/formik-connected/data-entry/DataBlock.tsx
packages/common-ui/lib/formik-connected/data-entry/DataRow.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/project/ProjectFormLayout.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/collection/project/edit.tsx
packages/dina-ui/pages/collection/project/view.tsx
packages/dina-ui/types/collection-api/resources/Project.ts

- Added Project Field Extensions section to project/view and project/edit pages
- Saving and loading should work on both pages

34850 Add field extension to project page

---

packages/dina-ui/components/seqdb/ngs-workflow/ngs-sample-select-coordinats-step/useNgsSelectCoordinatesControls.tsx
packages/dina-ui/components/storage/grid/StorageUnitGrid.tsx
packages/dina-ui/components/storage/grid/utils/useStorageUnitGridCoordinatesControls.tsx

- Changed usageType in useNgsSelectCoordinatesControls to "library-prep"
- Added support for library-prep in storage unit view page grid container

34956 Storage Unit view container grid support for library prep

---

packages/dina-ui/components/seqdb/pcr-workflow/__tests__/SangerPcrBatchItemGridStep.test.tsx
packages/dina-ui/components/seqdb/pcr-workflow/pcr-batch-plating-step/usePCRBatchItemGridControls.tsx
packages/dina-ui/components/seqdb/seq-workflow/SangerSeqReactionStep.tsx
packages/dina-ui/components/seqdb/seq-workflow/seq-batch-select-coordinats-step/useSeqSelectCoordinatesControls.tsx
packages/dina-ui/components/seqdb/seq-workflow/seq-reaction-step/useSeqReactionState.tsx
packages/dina-ui/components/storage/grid/utils/useStorageUnitGridCoordinatesControls.tsx

- Refactored all tabs in pcr-workflow to use material-sample-summary
- Refactored all tabs in seq-workflow to use material-sample-summary
- Refactored storage-unit/view grid to use material-sample-summary

34955 Sanger Workflows view improvements

---

packages/dina-ui/components/seqdb/seq-submission/SeqSubmissionFields.tsx
packages/dina-ui/components/seqdb/seq-submission/SeqSubmissionForm.tsx
packages/dina-ui/intl/seqdb-en.ts
packages/dina-ui/pages/seqdb/seq-submission/edit.tsx
packages/dina-ui/pages/seqdb/seq-submission/view.tsx
packages/dina-ui/types/seqdb-api/resources/SeqSubmission.ts

- Added seq-submission/edit page
- Refactored some components into their own files
- Added sequencingFacility relationship handling to seq-submission view/edit pages, should be able to save and load sequencingFacility

34951 Add sequence submission edit view

---

packages/dina-ui/components/storage/grid/StorageUnitGrid.tsx
packages/dina-ui/components/storage/grid/utils/useStorageUnitGridCoordinatesControls.tsx
packages/dina-ui/pages/collection/storage-unit/grid.tsx
packages/dina-ui/pages/seqdb/ngs-workflow/run.tsx
packages/dina-ui/pages/seqdb/pcr-workflow/run.tsx
packages/dina-ui/pages/seqdb/seq-workflow/run.tsx

- Clicking on Edit Contents grid button should now redirect to pages in edit mode
- Following pages should now be in edit mode, storage-unit/gird, ngs-workflow/run, pcr-workflow/run, seq-workflow/run

35008 Improve handling of edit mode for storage content

---

packages/common-ui/lib/column-selector/ColumnItem.tsx
packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/common-ui/lib/column-selector/ColumnSelectorList.tsx
packages/common-ui/lib/list-page/types.ts
packages/dina-ui/pages/export/data-export/export.tsx
packages/dina-ui/pages/export/data-export/useSavedExports.tsx
packages/dina-ui/types/user-api/resources/UserPreference.ts

- Added textbox to export mode to display the header name.

Support #34967 - Add support for column name customization on export

---

packages/dina-ui/pages/seqdb/pcr-batch/list.tsx

- Removed extraneous group column

35043 Double grouop column on PcrBatch list page

---

packages/dina-ui/components/bulk-edit/__tests__/useBulkEditTab.test.tsx
packages/dina-ui/components/managed-attributes/ManagedAttributesEditor.tsx
packages/dina-ui/page-tests/object-store/metadata/__tests__/edit.test.tsx

- Removed Visible Managed Attributes section
- Moved dropdown to add new attributes below current attributes

35080 Change Visible Managed Attributes editor

---

packages/dina-ui/components/workbook/SaveWorkbookProgress.tsx

- Now appends data to fields that are arrays instead of overriding

35135 Import Workbook append data replacing instead of appending

---

packages/common-ui/lib/index.ts
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/QueryBuilderElasticSearchExport.test.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/__snapshots__/QueryBuilderElasticSearchExport.test.tsx.snap
packages/common-ui/lib/table/ScientificNameCell.tsx
packages/dina-ui/components/collection/material-sample/organismUtils.ts
packages/dina-ui/components/collection/material-sample/useMaterialSampleRelationshipColumns.tsx
packages/dina-ui/components/index.ts

- Fix serialization logic to make sure that certain fields are always serialized as arrays if the original response was an array
- Updated test

35174 Can't edit Transactions

---

packages/common-ui/lib/formik-connected/FieldSet.tsx
packages/dina-ui/components/collection/GeoReferenceAssertionField.tsx
packages/dina-ui/components/collection/TabbedArrayField.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/collecting-event/ParseVerbatimToRangeButton.tsx
packages/dina-ui/components/collection/collecting-event/SetCoordinatesFromVerbatimButton.tsx
packages/dina-ui/components/collection/collecting-event/__tests__/ParseVerbatimToRangeButton.test.tsx
packages/dina-ui/components/collection/collecting-event/__tests__/SetCoordinatesFromVerbatimButton.test.tsx

- Removed extra Georeferencing header
- Changed large Convert buttons to icon buttons with tooltips
- Changed large Add/Remove Georef buttons to icon buttons with tooltips

35709 Improve collecting event view

---

packages/dina-ui/components/molecular-analysis/useMolecularAnalysisRun.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/useGenericMolecularAnalysisRun.tsx

- Handle loading and displaying molecular analysis information for usageType generic-molecular-analysis-item

35258 MolecularAnalysisRun view improvements

---

packages/dina-ui/components/object-store/metadata/MetadataDetails.tsx
packages/dina-ui/pages/object-store/object/external-resource-view.tsx

- Added tags section to view page
- Moved Resource External Url row to External Resource Details section

35369 Improve external resource page

---

packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx

- Added parsing on ";" delimiter and trimming white space
- Added handling of multiple field values, agents columns can now have multiple values

35336 Workbook multiple agents should be automatically selected

---

packages/dina-ui/components/molecular-analysis/useMolecularAnalysisRun.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/MolecularAnalysisRunStep.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/__mocks__/MolecularAnalysisMocks.ts
packages/dina-ui/components/seqdb/molecular-analysis-workflow/__tests__/MolecularAnalysisRunStep.test.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/useGenericMolecularAnalysisRun.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/types/seqdb-api/resources/molecular-analysis/MolecularAnalysisRunItem.ts

- Added Run Item Name column
- In edit, can set the MolecularAnalysisRunItem name
- Can load the MolecularAnalysisRunItem name TODO:
- Update the MolecularAnalysisRunItem name when MolecularAnalysisRun exists

35285 Allow name on molecular analysis run item

---

packages/dina-ui/components/molecular-analysis/MolecularAnalysisRunFormFields.tsx
packages/dina-ui/components/molecular-analysis/useMolecularAnalysisRun.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/MolecularAnalysisRunStep.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/QualityControlSection.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Refactored quality control code into QualityControlSection component to be reused

35416 Add Quality Control table to MolecularAnalysisRun view

---

packages/dina-ui/components/seqdb/molecular-analysis-workflow/MolecularAnalysisResultsStep.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Added a banner to tell users how many result attachments were found

35565 Provide feedback when sequence result link completes

---

packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/collecting-event/GeographySearchBox.tsx
packages/dina-ui/components/collection/collecting-event/GeographySearchDialog.tsx
packages/dina-ui/components/collection/global-names/GlobalNamesField.tsx
packages/dina-ui/components/collection/global-names/GlobalNamesSearchBox.tsx

- Changed hot link and View Details button to open links in new tab

35571 Open Catalogue of Life links in new tab

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/dina-user/__test__/view.test.tsx
packages/dina-ui/pages/dina-user/view.tsx
packages/dina-ui/types/user-api/resources/DinaUser.ts

- Added Admin Roles table to display user adminRoles

35705 Change user view to display isAdmin

---

packages/dina-ui/components/seqdb/molecular-analysis-workflow/QualityControlSection.tsx

- No longer visible in read only

35764 quality control paste zone visible in read only mode

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/dina-ui/pages/export/data-export/export.tsx
packages/dina-ui/pages/export/data-export/useSavedExports.tsx
packages/dina-ui/types/dina-export-api/index.ts
packages/dina-ui/types/dina-export-api/resources/DataExport.ts
packages/dina-ui/types/dina-export-api/resources/DataExportTemplate.ts

- Refactored useSavedExports hook to use dina-export-api/data-export-template
- Fixed saving, load, delete logic

35776 Move export templates from user to export api

---

packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx

- Added check to only add stateProvince if returned from OSM

35791 Don't set stateProvince if not returned from OSM

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/export/data-export/export.tsx
packages/dina-ui/pages/export/data-export/useSavedExports.tsx

- Added Select dropdown to set visibility options as suggested to Export Template creation modal
- Added dropdown to generic template usage section as well

35832 Export Templates add visibility options

---

packages/dina-ui/components/collection/collecting-event/useCollectingEvent.tsx
packages/dina-ui/components/collection/material-sample/__tests__/MaterialSampleForm.test.tsx
packages/dina-ui/components/collection/material-sample/useMaterialSample.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/types/collection-api/resources/CollectingEvent.ts

- Added logic to check if geographicPlaceNameSourceDetail has changed and remove it from the request if it has not changed.

Support #36030 - Issue saving material-sample with collecting-event from another group

---

Dockerfile

Updated Dockerfile with new Caddy version

Support #36113 Update Caddy to 2.8.4

---

packages/dina-ui/intl/dina-ui-en.ts

- Changed "Name" option to "Workflow Name" that is now searchable

36108 Make the search filter more descriptive for Molecular Analysis Name

---

packages/dina-ui/components/group/GroupFormLayout.tsx

- Group view page no longer makes request to agent-api/person if no id is available

36139 Invalid operations on group page

---

packages/common-ui/lib/formik-connected/sortable-select/SortableSelect.tsx

- Added logic to check edge case where select dropdown's options are not fully loaded from yet
- Should now show a multi select dropdown correctly instead of error

36389 Prepared By field in Workbook uploader throws error

---

packages/common-ui/lib/table/ReactTable.tsx

- Pasting run item names should now work for all run items based on how many is shown from pagination

36441 Can't paste more than 25 run item names

---

packages/common-ui/lib/formik-connected/DateField.tsx
packages/common-ui/lib/formik-connected/__tests__/DateField.test.tsx

- Updated the onBlur function for DateField to update the value on set.
- Added test cases to the DateField.test

Support #36533 - ObjectStore metadata page invalid date

---

packages/common-ui/lib/list-page/query-builder/query-builder-value-types/QueryBuilderManagedAttributeSearch.tsx

- Fixed issue with managedAttributeComponent being applied where it should't be.

Support #36577 - Managed Attribute Search Box Empty

---

packages/common-ui/common-ui-style.scss
packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/table/ReactTable.tsx
packages/dina-ui/components/object-store/exif-view/__test__/__snapshots__/view-exif.test.tsx.snap
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/workbook/__tests__/__snapshots__/generator.test.tsx.snap

- Added a fullscreen button for QueryPage tables (can be enabled using a prop for other tables as well)
- Added CSS to apply the fullscreen width 100%.
- Added edge case with objectstore preview so it still works correctly.
- Added horizontal scrollbar instead of just breaking the table if too large. Fixed headers being displayed weird in some cases.

Support #36144 - Query Page Fixes and Improvements

---

package.json
yarn.lock

-updated axios to version (1.11.0)
-form-data was updated to version 4.0.4 as a result of this

updated axios to version 1.11.0

---

packages/dina-ui/components/object-store/metadata/MetadataForm.tsx
packages/dina-ui/pages/object-store/metadata/external-resource-edit.tsx

-updated object subtype resource select field to use simpleSearchFilterBuilder

updated object subtype resource select field 

---

packages/common-ui/lib/custom-query-view/CustomQueryPageView.tsx
packages/dina-ui/components/project/ProjectFormLayout.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/collection/project/__test__/view.test.tsx

-added params to customQueryViewPage to show a button with a link
-added link to list of attached material samples in project view page 
-added unit tests for project view page, for project attributes, attachments, and attached material samples

Support #36826 add link to linked material samples in project view page

---

packages/common-ui/lib/formik-connected/GroupedCheckBoxFields.tsx
packages/common-ui/lib/util/__tests__/resourceDifference.test.ts
packages/common-ui/lib/util/resourceDifference.ts
packages/dina-ui/page-tests/loan-transaction/transaction/__tests__/edit.test.tsx
packages/dina-ui/pages/loan-transaction/transaction/edit.tsx

- Fixed the issue with the returnNullForMissingResource not being set to true (instead of throwing an error)
- Working on adding test coverage for this case.

Support #36843 - Transaction issue with material sample loading
