components/resource-select/ResourceSelect.tsx
pages/pcr-primer/__tests__/edit.test.tsx

https://redmine.biodiversity.agr.gc.ca/issues/15534
-Changed ResourceSelect's usage of Promise.then to async/await,
to keep consistent with the rest of the code. Mixing the two may have
caused conflicts with a test's async mock function.
-Moved the test's mockGet implementation into its declaration because
there is only one mock implementation anyway.
-Changed jest.resetAllMocks(); to jest.clearAllMocks(); because the
mocks don't need to be de-implemented between tests.

In progress Bug #15534 PCR primer edit page tests sometimes fail

---

packages/common-ui/lib/collapser/__tests__/useCollapser.test.tsx
packages/common-ui/lib/collapser/useCollapser.tsx
packages/objectstore-ui/components/metadata/MetadataDetails.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19348
-Made the collapser open by default.
-Aligned the collapser to the left of the text.

Feedback Support #19348 Improve collapser arrows in Objectstore UI

---

Dockerfile
packages/dina-ui/Dockerfile
packages/dina-ui/dev.Caddyfile
packages/dina-ui/prod.Caddyfile
packages/seqdb-ui/dev.Caddyfile
packages/seqdb-ui/prod.Caddyfile
seqdb-ui.Dockerfile

https://redmine.biodiversity.agr.gc.ca/issues/19581
-Changed Caddy configs port to 8080 so it can run on openshift without the permission error.
-Added missing dev.Caddyfile for seqdb.
-Updated Caddy images to 2.0.0-alpine.

Feedback Support #19581 Allow Caddy port to be configured

---

packages/common-ui/lib/account/AccountProvider.tsx
packages/common-ui/lib/account/__tests__/AccountProvider.test.tsx
packages/dina-ui/page-tests/object-store/upload.test.tsx
packages/dina-ui/pages/object-store/object/list.tsx
packages/dina-ui/pages/object-store/upload.tsx
packages/dina-ui/test-util/mock-app-context.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19671
-Added conversion from keycloak's group name format to bare group names, with only unique values in the dropdowns.

Feedback Support #19671 Add support for Keycloak roles per group

---

packages/common-ui/lib/formik-connected/GroupedCheckBoxFields.tsx
packages/common-ui/lib/table/QueryTable.tsx

https://redmine.biodiversity.agr.gc.ca/issues/19812
-Aligned header text to the left.
-Centered the checkbox header text to match the checkbox cells.

Feedback Support #19812 Align table header text to left

---

packages/dina-ui/next.config.js
packages/seqdb-ui/next.config.js

https://redmine.biodiversity.agr.gc.ca/issues/19880
-Enabled setImmediate polyfill in webpack config.

Feedback Bug #19880 Group filter fails in the browser

---

packages/common-ui/lib/formik-connected/DateField.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/pages/object-store/managedAttributesView/detailsView.tsx
packages/dina-ui/pages/object-store/managedAttributesView/listView.tsx
packages/dina-ui/types/objectstore-api/resources/ManagedAttribute.ts

List view:
- Remove CreatedDate and add CreatedBy
- Description renders only the content if there is only one language
Details view
- Expand description fields
- Display CreatedOn and CreatedBy
- Made date field not clearable in readonly mode.

Support_19955_Managed_Attributes_view_improvements

---

packages/common-ui/lib/formik-connected/GroupedCheckBoxFields.tsx
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/tooltip/Tooltip.tsx

-  Add aria-describedby to default and not default trigger elements for screenreader to attach to tooltip
-  Add alt="" to default trigger element image

Support 21228 ISB EIS WCAG2 1.1.1 Non-text content(Level A)

---

packages/common-ui/lib/bulk-data-editor/BulkDataEditor.tsx
packages/common-ui/lib/bulk-data-editor/useHeaderWidthFix.tsx

-Added useEffect hook to manually fix the header width on columns change.
-Added css zIndex fix so the row headers don't overlap the dropdown menus.

Feedback Support 21256

---

packages/common-ui/lib/filter-builder/__tests__/rsql.test.ts
packages/common-ui/lib/filter-builder/rsql.ts
packages/common-ui/lib/list-page-layout/ListPageLayout.tsx

-Converted the resource ID to string so 'null' is searched correctly.
-Updated ListPageLayout so an rsql conversion error can't crash the page, you will get an error logged instead and the FilterBuilder is ignored.

Feedback 21416

---

packages/common-ui/lib/formik-connected/SelectField.tsx
packages/dina-ui/components/group-select/GroupSelectField.tsx
packages/dina-ui/pages/collecting-event/edit.tsx
packages/dina-ui/pages/collecting-event/list.tsx
packages/dina-ui/pages/object-store/object/list.tsx

-Fixed bug that was disabling the groupo selects:
-Removed defaultValue prop from SelectField. It shouldn't be needed now that the current group is always included in the GroupSelect options.
-Added group filter rsql to collecting event list page.
-Removed showAnyOption from collecting event edit page.

Feedback 21627

---

packages/common-ui/lib/key-value-table/KeyValueTable.tsx
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/table/react-table-style.css
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/dina-user/__test__/view.test.tsx
packages/dina-ui/pages/_app.tsx
packages/dina-ui/pages/dina-user/view.tsx
packages/dina-ui/types/user-api/resources/DinaUser.ts

-Made KeyValueTable more customizable.
-Moved QueryTable css to a separate css file so it applies to other ReactTable components.
-Added RolesPerGroupTable to user view page.

Support_21822_Display_roles_per_group

---

packages/dina-ui/pages/collection/collecting-event/edit.tsx

Changed onSubmit to only check for a georeferencedBy array instead of checking the length, so empty arrays are allowed.

Feedback 22037

---

packages/dina-ui/pages/collection/collecting-event/edit.tsx

Changed the setFieldValue call to default to null instead of undefined when the province field is blank.
Setting a form field to undefined will leave it unchanged from the previous value when submitted to the back-end.

Feedback 22215

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/SetCoordinatesFromVerbatimButton.tsx

-Made GeographySearchBox not render in readOnly mode.
-Made GeographySearchBoxSetCoordinatesFromVerbatimButton not render in readOnly mode.
-Got rid of the duplicate SetCoordinatesFromVerbatimButton in the Georeferencing section.

Feedback 22245

---

packages/dina-ui/pages/collection/collecting-event/edit.tsx

-Set the Collecting Event ID after saving to prevent duplicate POST requests after an error.

Feedback 22260

---

packages/dina-ui/components/object-store/metadata/MetadataDetails.tsx
packages/dina-ui/components/object-store/metadata/MetadataPreview.tsx
packages/dina-ui/components/object-store/stored-object-gallery/StoredObjectGallery.tsx
packages/dina-ui/components/revisions/revision-row-configs/metadata-revision-row-config.tsx
packages/dina-ui/page-tests/object-store/object/__tests__/view.test.tsx
packages/dina-ui/pages/object-store/object/view.tsx
packages/dina-ui/types/objectstore-api/resources/Metadata.ts

- Update object gallery thumbnail to use the new end point instead of getting the thumbmail response via acDerivedFrom

Support 22138 thumbnail download endpont

---

packages/dina-ui/components/collection/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/GeographySearchBox.tsx

-Remove DMS buttons from verbatim locality and current place search input

Support-22408-removed-DMS-buttons-where-it-should-not-be

---

packages/dina-ui/components/collection/useCollectingEvent.ts
packages/dina-ui/components/object-store/attachment-list/AttachmentReadOnlySection.tsx
packages/dina-ui/components/object-store/attachment-list/__tests__/attachment-modal.test.tsx
packages/dina-ui/components/object-store/attachment-list/attachments-modal.tsx
packages/dina-ui/intl/dina-ui-en.ts

-Added fallback message to UI (Collecting Event and Catalogued Object edit and view pages) when the object-store is unavailable.
-Fixed issue with Catalogued Object edit page where Collecting Event attachments weren't showing up; Made the attachments list reinitizlize when the fetched Collecting Event changes.

Feedback 22420

---

packages/common-ui/lib/formik-connected/SelectField.tsx
packages/common-ui/lib/formik-connected/__tests__/SelectField.test.tsx
packages/dina-ui/components/group-select/GroupSelectField.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/dina-user/__test__/edit.test.tsx
packages/dina-ui/pages/dina-user/edit.tsx
packages/dina-ui/pages/dina-user/view.tsx

-Changed the dropdown to only allow one group at a time.
-Kept the "isMulti" prop because the back-end could possibly provide multiple roles, but changing the value in the editor only allows one role.

Feedback 22683

---

packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx

-Removed the requirement for either Material Sample Name or Catalog Number.
-Changed list view to show the first non-blank value from: materialSampleName, dwcOtherCatalogNumbers, uuid.

Feedback 22864

---

packages/dina-ui/components/storage/BrowseStorageTree.tsx

Hid the expander button when there are no storage children.

Feedback 23499

---

packages/common-ui/lib/formik-connected/FieldWrapper.tsx
packages/common-ui/lib/formik-connected/__tests__/FieldWrapper.test.tsx
packages/dina-ui/components/collection/CollectingEventFormLayout.tsx

-Made FieldWrapper use the templateCheckboxFieldName when present to check if the field is enabled/disabled by the template.
-Added more tests for FieldWrapper.

Feedback 23619

---

packages/common-ui/lib/intl/common-ui-en.ts
packages/common-ui/lib/list-page-layout/ListPageLayout.tsx
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/table/__tests__/QueryTable.test.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx

-Removed the 'undefined' column from the material sample list.
-Changed the QueryTable error so it renders in the table body instead of covering the columns/buttons.

Feedback 25294

---

packages/common-ui/common-ui-style.css
packages/common-ui/lib/formik-connected/FieldSet.tsx

Provided customization to h2 font size to make it smaller than h1 title and to the top and bottom margins to provide balanced distancing between fieldset border and content.

Update to add h2 heading to titles of fieldsets

---

packages/common-ui/lib/formik-connected/DateField.tsx
packages/common-ui/lib/formik-connected/FieldWrapper.tsx
packages/common-ui/lib/formik-connected/__tests__/DateField.test.tsx
packages/common-ui/lib/intl/common-ui-en.ts

-No more autocorrect.
-Shows an error message on blur and on form submit when there is either an invalid date (like 2021-02-29) or bad format (like '20210105' or 'asdfasdf').
-Added an error boundary to the FieldWrapper so an error in one field doesn't kill the whole page.

Changed DateField:

---

packages/common-ui/lib/api-client/ApiClientContext.tsx
packages/common-ui/lib/api-client/__tests__/ApiClientContext.test.ts
packages/dina-ui/components/object-store/attachment-list/AttachmentsField.tsx
packages/dina-ui/components/object-store/attachment-list/__tests__/AttachmentsField.test.tsx

-Added dataloader usage to bulkGet to batch together find-one requests with the same ID.
-Updated Attachments Editor to remove duplicate attachment IDs when they are added.

Feedback 25658

---

packages/common-ui/lib/formik-connected/MetersField.tsx
packages/common-ui/lib/formik-connected/__tests__/MetersField.test.tsx

Added regex to pre-clean the input for values the mathjs parser can't handle
- Abbreviations: (ft. -> ft)
- quotes/apostrophes: (5' -> 5 feet)
-Added more tests.

Feedback 25677

---

packages/common-ui/lib/formik-connected/AssociatedMaterialSampleSearchBox.tsx
packages/dina-ui/components/collection/MaterialSampleAssociationsField.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx

-Changed listRef + d-none usage to use useState.
-Wrapped the table in a FastField to avoid unnecessary re-renders.
-Added the is-invalid class when the associatedSample is invalid so the error message shows below the Search box

Feedback 25963

---

packages/dina-ui/components/bulk-material-sample/MaterialSampleGenerationForm.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleGenerationForm.test.tsx
packages/dina-ui/components/bulk-material-sample/bulk-edit-tab.tsx
packages/dina-ui/components/group-select/GroupSelectField.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/bulk-create.test.tsx
packages/dina-ui/pages/collection/material-sample/bulk-create.tsx
packages/dina-ui/pages/collection/material-sample/edit.tsx
packages/dina-ui/pages/collection/workflow-template/run.tsx

-Added the group select (invisible if you only have 1 group) to the bulk create form. (accessed by the Split or Create Multiple New buttons).
-Enabled editing the group field in bulk edit.
-Only enable the auto group selection (last selected group from localstorage) on Material Sample for the edit page and workflow run pages. Disabled for template creation, and bulk edit pages.

Feedback 26236

---

packages/dina-ui/components/table/__tests__/thumbnail-cell.test.tsx
packages/dina-ui/components/table/thumbnail-cell.tsx
packages/dina-ui/pages/object-store/object/list.tsx
packages/dina-ui/types/objectstore-api/resources/Metadata.ts

- Refactored thumbnail-cell to use original object into get
- Changed the passed in fileIdentifierField and bucketField from object/list to destructure the object instead of destructuring original in thumbnail-cell
- Removed the data property from MetadataAttributes
- This will make the code for object/list and AttachmentsTable more consistent

28612 thumbnails not appearing for embedded object store upload

---

packages/dina-ui/components/collection/form-template/useMaterialSampleFormTemplateSelectState.tsx

- Now uses the local storage Form Template's UUID to retrieve Form from back end
- This should allow Material Sample to reflect any changes made to Form Template

28998 Form Template useLocalStorage use UUID

---

packages/common-ui/lib/util/useThrottledFetch.tsx
packages/dina-ui/components/collection/form-template/useMaterialSampleFormTemplateSelectState.tsx
packages/dina-ui/components/collection/global-names/GlobalNamesSearchBox.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/intl/dina-ui-fr.ts

- Removed Virus Name checkbox and code
- Now correctly finds virus names by default
- Fixed a bug when a Form Template is saved in Material Sample local storage but the Form Template is deleted

28919 Remove Virus Name checkbox on name search

---

packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/storage/StorageLinker.tsx
packages/dina-ui/components/storage/StorageUnitChildrenViewer.tsx

-Added a create storage mode, disabled it for storageUnitChildrenViewer and enabled it for material samples page -Recursive problem no longer exists on add a new storage unit -Need to make sure that it is the children viewer that should be disabled and not the storage unit form

Support #29359 Create Storage unit recursive view

---

packages/dina-ui/components/object-store/file-upload/FileUploadProvider.tsx
packages/dina-ui/components/object-store/metadata/useMetadata.tsx
packages/dina-ui/intl/dina-ui-en.ts
packages/dina-ui/page-tests/object-store/__tests__/upload.test.tsx
packages/dina-ui/pages/_app.tsx
packages/dina-ui/test-util/mock-app-context.tsx

1. Handle http status 403 error.
2. Turn unsupported file type error message to support multiplelingual message.
3. Fixed the undefined primary key get issue.

29175 handle 403 error

---

packages/dina-ui/pages/object-store/object/view.tsx

- Fixed Object Store's attached material samples table to use the same column as Assemblage
- Scientific Name column should appear in the table just like Assemblage's table

29680 Improve attached Material Samples table in object store

---

packages/dina-ui/components/workbook/WorkbookColumnMapping.tsx
packages/dina-ui/components/workbook/utils/FieldMappingConfig.json
packages/dina-ui/components/workbook/utils/useFieldConverters.ts
packages/dina-ui/components/workbook/utils/workbookMappingUtils.ts

- Changed Material Sample Type field mapping config to vocabulary with an endpoint
- Refactored some data type conversion code
- Added workbook vocabulary validation, now throws error if vocab in workbook not in endpoint
- Fixed small bug with error message row index

29954 Workbook Material Sasmple Type Validation

---

packages/common-ui/lib/formik-connected/CreatableSelectField.tsx

- Changed Add keyword in dropdown to Use
- Hitting Enter key uses the new custom value
- Clicking away from the dropdown uses the new custom value

30362 Protocol Data view incomplete

---

packages/dina-ui/components/bulk-edit/__tests__/useBulkEditTab.test.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/collection/material-sample/__tests__/MaterialSampleForm.test.tsx
packages/dina-ui/page-tests/collection/form-template/__tests__/edit.test.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx
packages/dina-ui/types/collection-api/resources/form-legends/MaterialSampleForm.ts

- Commented out logic to display Acquisition Event in Material Form Nav bar
- Commented out logic to display Acquisition Event in Material Sample edit
- Commented out logic to display Acquisition Event in Material Sample view
- Only commenting out for now instead of removing because the actual removal needs to be confirmed in another release

29988 Hide acquisition event

---

packages/dina-ui/components/bulk-metadata/UploadingMetadataBulkEditor.tsx
packages/dina-ui/components/object-store/metadata/MetadataUpload.tsx
packages/dina-ui/types/objectstore-api/resources/Metadata.ts

- Changed default value of acMetadataCreator from null to undefined when agentId not available
- Should no longer throw internal server error when agentId not available

30234 Can't upload attachment in Project

---

packages/common-ui/lib/tooltip/Tooltip.tsx

- Hovering over tooltip correctly shows tooltip bubble over modal now

29998 Hover tooltip for Add Person in Modal not visible

---

packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleIdentifiersSection.tsx
packages/dina-ui/page-tests/collection/form-template/__tests__/edit.test.tsx
packages/dina-ui/types/collection-api/resources/form-legends/MaterialSampleForm.ts

- Removed visibility check box for Group, Primary ID, Collection in Form Template
- These 3 fields should always be visible now

29893 Form Template mandatory fields for all templates

---

packages/dina-ui/components/button-bar/nav/nav.css
packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/intl/dina-ui-en.ts

1. Renamed Collections dropdown to Collection
2. Moved Collection item back to main dropdown
3. Moved Collection Method to Controlled Vocabulary submenu

30727 Fixes for Controlled Vocabulary submenu

---

packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchExport.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/__snapshots__/QueryBuilderElasticSearchExport.test.tsx.snap

- Added ".keyword" to the group, the issue was the "-" in the group splitting it.
- Updated snapshot.

Support #30769 - Search on philip's lab group not working

---

packages/dina-ui/components/object-store/file-view/FileView.tsx

- Fixed Original download file name to use originalFilename
- Thumbnail name should also be consistent with what it was previously

31324 Regression in download functionality

---

packages/common-ui/lib/filter-builder/FilterRow.tsx

FilterRow components should now shrink with window width such that horizontal scrolling should no longer be necessary to see AND/OR buttons

31385 filter table doesn't align with the rest of the page

---

packages/dina-ui/components/collection/material-sample/GenerateLabelDropdownButton.tsx

- Barcode now produces sample's uuid instead of name
- Barcode only included in label if template includesBarcode field is true

31602 Label barcode payload should use uuid instead of name

---

packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/pages/index.tsx

- Moved everything except for Users out of Management menu into new Controlled Vocabulary Menu
- Combined Controlled Vocabulary from Collection with new menu
- Added a Controlled Vocabulary section with list of links on the Home page to be consistent with other dropdown menus

31992 Move Controlled Vocabulary out of Management menu

---

.github/workflows/ci.yml
packages/common-ui/lib/formik-connected/__tests__/CheckBoxField.test.tsx

- Bumped up to 8 test chunk runners (0 based number, changed to 7)
- Testing fail-fast set to false.
- Build step no longer depends on the test-chunks finishing.
- Broke a test on purpose for testing.

Support #32030 - CI Improvements

---

packages/common-ui/lib/column-chooser/ColumnChooser.tsx
packages/common-ui/lib/column-chooser/GroupedCheckboxWithLabel.tsx
packages/common-ui/lib/list-page-layout/bulk-buttons.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/dina-ui/pages/collection/material-sample/export.tsx

- Column selection on Export page now uses selected columns from Material Sample list page
- Column selection menu now always visible on Export page, no longer needs Select Columns button
- Fixed bug related to selectColumn that caused Select All button to behave incorrectly
- Now no longer has Select Column option and Select All button works correctly

32018 Improvements to export view

---

packages/common-ui/lib/formik-connected/data-entry/DataEntryUtils.tsx
packages/common-ui/lib/formik-connected/data-entry/DataEntryViewer.tsx
packages/dina-ui/components/collection/collecting-event/CollectingEventFormLayout.tsx
packages/dina-ui/components/collection/collecting-event/useCollectingEvent.tsx
packages/dina-ui/components/collection/material-sample/MaterialSampleForm.tsx
packages/dina-ui/components/collection/material-sample/useMaterialSample.tsx
packages/dina-ui/components/revisions/revision-row-configs/collectingevent-revision-config.tsx
packages/dina-ui/components/revisions/revision-row-configs/material-sample-revision-configs.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx
packages/dina-ui/types/collection-api/resources/CollectingEvent.ts
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

- Added comments to the DataEntryUtils.
- Added a check to the processExtensionValuesLoading to see if it has already been processed, if so don't re-process it.
-  Changed all "extensionValuesForm" back to "extensionValues" since it was causing issues with the form templates - added the check in processExtensionValuesLoading to prevent it from redoing it multiple times.

Support #32196 - Form template not working

---

packages/common-ui/common-ui-style.scss
packages/common-ui/lib/list-page/query-builder/query-builder-core-components/QueryConjunctionSwitch.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-core-components/__tests__/__snapshots__/QueryConjunctionSwitch.test.tsx.snap
packages/common-ui/lib/list-page/query-builder/useQueryBuilderConfig.tsx

- If only one rule is inside of a group (including the root group) it will now no longer display the conjunction switch, the line will also be removed until more than one rule is there.
- Moved the position and color of the toggle group slightly so it aligns with the line.
- Toggle switch text is now centered vertically with the button.

Support #32197 - Simplify query builder

---

packages/common-ui/lib/custom-query-view/CustomQueryPageView.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/dina-ui/components/project/ProjectFormLayout.tsx
packages/dina-ui/components/seqdb/ngs-workflow/NgsSampleSelectionStep.tsx
packages/dina-ui/components/seqdb/pcr-workflow/SangerSampleSelectionStep.tsx
packages/dina-ui/components/transaction/MaterialSampleTransactionList.tsx
packages/dina-ui/pages/collection/assemblage/edit.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx
packages/dina-ui/pages/loan-transaction/transaction/edit.tsx
packages/dina-ui/pages/loan-transaction/transaction/list.tsx
packages/dina-ui/pages/object-store/object/list.tsx
packages/dina-ui/pages/object-store/object/view.tsx

- Custom Views now have column selection turned off (not supported yet anyway)
- Instead of using indexName for local storage, each QueryPage will now have a uniqueName so the settings can be stored per table.

Support #32332 - Material sample children not loading

---

packages/dina-ui/components/storage/StorageFilter.tsx
packages/dina-ui/components/storage/__tests__/BrowseStorageTree.test.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitChildrenViewer.test.tsx

- Changed filter to generate an IN with all of the options instead.
- Updated the test for the new RSQL being generated.

Support #32335 - Add existing storage unit group rsql is incorrect

---

packages/dina-ui/components/object-store/attachment-list/AttachmentsField.tsx

- Looks like sometimes react rerenders causes items to be added twice in a list
- Now filters for unique metadata ids

32476 Collecting event attach existing doubling attachments

---

packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/table/ReactTable.tsx
packages/dina-ui/components/collection/material-sample/SamplesView.tsx
packages/dina-ui/components/collection/material-sample/ScheduledActionsField.tsx
packages/dina-ui/components/revisions/RevisionsPageLayout.tsx
packages/dina-ui/components/seqdb/ngs-index/NgsIndexField.tsx

- Fix incorrect use of states, now use state passed to ReactTable from QueryPage
- Fall back to ReactTable internal state otherwise
- Clicking on QueryPage reset should now correctly reset the sort indicators on column headers
- Refactored state names

32753 Reset arrow on column headers when search is reset

---

packages/common-ui/lib/list-page/query-builder/query-builder-value-types/QueryBuilderManagedAttributeSearch.tsx
packages/common-ui/lib/list-page/reload-last-search/useLastSavedSearch.tsx
packages/common-ui/lib/list-page/saved-searches/SavedSearch.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Default loaded in state is now set to true when last loaded has been already loaded in, default search will be skipped now.
- Query error is cleared when a new search is selected and redetermined.

Bug #32940 - Issue with managed attribute saved search with last saved search or default searches

---

packages/common-ui/lib/intl/common-ui-en.ts
packages/common-ui/lib/list-page-layout/bulk-buttons.tsx
packages/dina-ui/components/object-store/file-view/FileView.tsx
packages/dina-ui/pages/data-export/export.tsx
packages/dina-ui/types/objectstore-api/index.ts
packages/dina-ui/types/objectstore-api/resources/ObjectExport.ts

- Added Export Objects button to Export page if coming from Object Store
- Export Objects button only enabled if user has selected records from the Object Store list page
- Clicking on the Export Objects button will POST to objectstore-api/object-export, should receive 201 code
- Then sends GET request  to dina-export-api to download the zip
- The downloaded file should be LARGE_IMAGE derivative if available, otherwise Original
- If more than 100 records are selected, only downloads the first 100

32888 Add Export Objects option on object store export

---

packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/QueryBuilderAutoSuggestionSearch.test.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/QueryBuilderBooleanSearch.test.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/QueryBuilderNumberSearch.test.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/QueryBuilderTextSearch.test.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/__snapshots__/QueryBuilderAutoSuggestionSearch.test.tsx.snap
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/__snapshots__/QueryBuilderBooleanSearch.test.tsx.snap
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/__snapshots__/QueryBuilderNumberSearch.test.tsx.snap
packages/common-ui/lib/list-page/query-builder/query-builder-value-types/__tests__/__snapshots__/QueryBuilderTextSearch.test.tsx.snap

- Migrated the Boolean and Number Query Search tests to use "React-testing-library" instead of enzyme.
- Started working on the new Auto Suggestion Query tests, with mocks to the elastic search request/response.

Support #32813 - Autocomplete on material sample type not working

---

packages/common-ui/lib/list-page/saved-searches/SavedSearch.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Moved the saved search name to it's own line
- Applied bold to the "Are you sure you want to delete:" part with the name unbolded

Support #33028 - Improve the Saved Search Deletion Dialog

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/common-ui/lib/list-page-layout/DataExportListPageLayout.tsx
packages/common-ui/lib/list-page-layout/bulk-buttons.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/table/QueryTable.tsx
packages/common-ui/lib/table/ReactTable.tsx
packages/dina-ui/pages/data-export/export.tsx
packages/dina-ui/types/dina-export-api/resources/DataExport.ts

- Refactored Export button from ColumnSelector menu to Export page
- Export button now in button bar of Export page
- Added "name" attribute to DataExport interface
- Added "exportType" attribute to DataExport interface
- Added "name" TextField to Export page, user can now enter name
- Clicking on Export button now sends request with "name" as part of payload
- The downloaded csv file will have "name" as file name
- Added "name" column to Data Exports list table

33108 Allow to set name on export

---

packages/common-ui/lib/formik-connected/data-entry/DataEntryViewer.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

- Added Form Template dropdown selection to view page button bar
- Only visibility applied, default values not used
- Selecting no Form Template displays all fields like edit page
- Direct Material Sample children section, Transaction section, along with other fields that cannot be hidden are always displayed

32220  Form Template support for Material Sample view page

---

packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/QueryBuilderElasticSearchValidator.tsx
packages/common-ui/lib/list-page/query-builder/query-builder-elastic-search/__tests__/QueryBuilderElasticSearchValidator.test.tsx

- Fixed the error.
- Added test coverage for the QueryBuilderElasticSearchValidator for an empty query tree.
- Added test coverage for date validation.

Support #33339 - UI Crash when delete a filter

---

package.json
packages/scripts/intl-support/__tests__/messages-csv-export.test.ts
yarn.lock

- Resolving pdfjs-dist to 4.2.67
- Updated xlsx to use a third party tool that pulls xlsx from their self host git repo, this allows us to keep using npm registry

33839 Dependencies update

---

packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx
packages/dina-ui/components/workbook/utils/FieldMappingConfig.ts
packages/dina-ui/components/workbook/utils/workbookMappingUtils.ts
packages/dina-ui/types/collection-api/resources/MaterialSample.ts

- Added hostOrganism with attributes name and remarks to FieldMappingConfig
- Can now add hostOrganism.name and hostOrganism.remarks columns in workbook upload
- Can also use "host organism" or "hostorganism" for instead of hostOrganism.name
- Fixed bug where grouping name in the select field did not have a space between host organism

33842 Add host organism to workbook upload

---

packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx
packages/dina-ui/components/workbook/utils/workbookMappingUtils.ts

- Now no longer auto selects collector's display name if there is a column header with "display name"

33941 Workbook upload avoid autoselect when more than 1 option

---

packages/common-ui/lib/field-header/FieldHeader.tsx
packages/common-ui/lib/formik-connected/FieldWrapper.tsx
packages/common-ui/lib/formik-connected/__tests__/__snapshots__/AutoSuggestTextField.test.tsx.snap
packages/common-ui/lib/resource-select/ResourceSelect.tsx
packages/dina-ui/components/managed-attributes/ManagedAttributeField.tsx
packages/dina-ui/components/managed-attributes/ManagedAttributesViewer.tsx

- Now displays tooltip for object store managed attributes in object/view page
- Tooltip should corresponding to locale

34066 Display managed attributes tooltips in object store view

---

packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/table/Pagination.tsx
packages/common-ui/lib/table/ReactTable.tsx
packages/common-ui/lib/table/react-table.css
packages/dina-ui/components/seqdb/ngs-workflow/NgsSampleSelectionStep.tsx
packages/dina-ui/components/seqdb/pcr-workflow/SangerSampleSelectionStep.tsx
packages/dina-ui/pages/seqdb/ngs-workflow-pooling/run.tsx
packages/dina-ui/pages/seqdb/ngs-workflow/run.tsx
packages/dina-ui/pages/seqdb/pcr-workflow/run.tsx

- Selection mode will now use smaller pagination buttons. These buttons will only display the icons for small tables.
- Fixed issues with button bar on workflows.
- Fixed issue with material sample query page view trying to use the pagination from the selection mode.

Support #34095 - New pagination options look awkward on selection mode

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/common-ui/lib/column-selector/ColumnSelectorUtils.tsx
packages/common-ui/lib/custom-query-view/CustomQueryPageView.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/dina-ui/components/collection/material-sample/useMaterialSampleRelationshipColumns.tsx

- Enabled ColumnSelector in material sample children table
- Fixed infinite loading bug
- Fixed column ids missing
- Filtered out collecting event menu options since children can't have a collecting event

33342 Allow to select columns on material sample children list

---

package.json
packages/dina-ui/components/bulk-material-sample/MaterialSampleGenerationForm.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleGenerationForm.test.tsx
packages/dina-ui/page-tests/collection/material-sample/__tests__/bulk-create.test.tsx

- Removed Generate Batch Option
- Removed tabs, now only has 1 generation mode (series)
- Selecting Collection now fills base name with Collection Code
- When customizing Material Sample name in Preview, the names should now be correctly used in bulk edit mode

34503 Clean Bulk Create material sample page

---

packages/common-ui/lib/search/useAutocompleteSearchButFallbackToRsqlApiSearch.ts
packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx

- Added resource "type" to elasticSearchResult
- Typing in the "Prepared By" field and selecting a "Person" should no longer throw error on save

34404 Bulk Edit Prepared By not working

---

packages/dina-ui/components/bulk-material-sample/MaterialSampleSplitGenerationForm.tsx
packages/dina-ui/pages/collection/material-sample/bulk-split.tsx

- State is now controlled by the parent component instead using the existing formTemplateID state.
- Changing the split configuration will now re-generate the preview.

Bug #34544 - Split select doesn't preserve the correct split config name

---

packages/dina-ui/pages/export/data-export/export.tsx

- Added a try/catch block that will set the error message if caught.
- Error messages are cleared when trying to export again.

Support #34329 - Handle object export errors more gracefully

---

packages/dina-ui/components/bulk-material-sample/MaterialSampleSplitGenerationForm.tsx
packages/dina-ui/components/collection/form-template/useMaterialSampleFormTemplateSelectState.tsx

- Users can now unselect Form Template in bulk edit screen after the bulk-split config screen
- Added small change to disable Split button on split configs screen if no split config is selected i.e if user selected a material sample with no valid split config and selected bulk split

34543 Unselect Form Template from material sample split

---

packages/dina-ui/components/storage/StorageUnitForm.tsx
packages/dina-ui/page-tests/collection/storage-unit/__tests__/edit.test.tsx

- Saving storage unit without interacting with Generic toggle now saves without error

34530 Storage unit creation isGeneric must not be null error

---

packages/common-ui/lib/search/useAutocompleteSearchButFallbackToRsqlApiSearch.ts
packages/dina-ui/components/collection/material-sample/MaterialSampleBreadCrumb.tsx
packages/dina-ui/components/resource-select-fields/resource-select-fields.tsx
packages/dina-ui/pages/collection/material-sample/view.tsx

- Removed the "type" prop from useAutoCompleteSearch hook as it's not needed anymore since the auto-complete api returns this value now
- Minor change to material sample view to fall back on id if primary id not available in view page
- "Prepared By" selector should not throw an error on material sample saving if an agent was chosen by typing into the filter

34613 Elastic Search Autocomplete use resource type from search-api

---

packages/dina-ui/components/bulk-material-sample/MaterialSampleGenerationForm.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleGenerationForm.test.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Added sourceset field when adding multiple Material Samples.
- Added tooltip to the field.
- If set, the material samples will have the sourceSet applied and it can be searched on.

Support #34649 - Add sourceSet to bulk create material sample

---

packages/dina-ui/components/object-store/index.ts
packages/dina-ui/components/object-store/metadata/MetadataBadges.tsx
packages/dina-ui/components/object-store/metadata/MetadataForm.tsx
packages/dina-ui/components/object-store/metadata/MetadataPreview.tsx
packages/dina-ui/components/tag-editor/TagSelectField.tsx

- Added MetatadataBadges component with TagSelectReadOnly
- Object Store view page should now have a tag badge if one was added from edit page

34427 Tag missing from object store detail page

---

packages/common-ui/lib/list-page/reload-last-search/useLastSavedSearch.tsx

- Updated the lastSavedSearch to ensure the setQueryBuilderTree is also called (not just the submitted version)
- Don't need to run save the states twice which causes some issues.

Bug #34806 - Part of AND query ignored

---

packages/dina-ui/components/seqdb/pcr-workflow/PcrReactionTable.tsx
packages/dina-ui/components/seqdb/seq-workflow/seq-reaction-step/SeqReactionDndTable.tsx
packages/dina-ui/pages/seqdb/seq-batch/edit.tsx

- Removed storageRestriction layout field from seq-workflow/run SEQ Batch tab
- Added sorting to the PCR reaction table in seq-workflow to be consistent with pcr-workflow
- Tested adding material samples and moving them to Select Coordinates table, everything seems to be working correctly

34819 SeqBatch view update

---

packages/common-ui/lib/index.ts
packages/common-ui/lib/visibility/useIsVisible.tsx
packages/dina-ui/components/object-store/file-view/FileView.tsx

- Created a new hook called useIsVisible which lets you check if a element on the page has been loaded into the view port.
- File view has been refactored to disable the request if it's not in the view port yet. (Added a buffer of 300px so it will start loading some outside of the view port)

Support #34922 - Check image lazy loading in object store

---

packages/common-ui/lib/column-selector/ColumnSelectorUtils.tsx
packages/common-ui/lib/column-selector/__tests__/ColumnSelectorUtils.test.tsx
packages/dina-ui/components/collection/VocabularySelectField.tsx
packages/dina-ui/pages/collection/material-sample/list.tsx

- Updated the generateColumnPath to include the relationshipName if it's a relationship.
- Updated the test coverage.
- Updated the parsing of the column paths to read the relationship name and link it to the correct relationship field config.

Support #34965 - Issue with dynamic field configuration on parent material samples

---

packages/dina-ui/components/workbook/column-mapping/WorkbookFieldSelectField.tsx
packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx
packages/dina-ui/components/workbook/utils/FieldMappingConfig.ts

- Add Collecting Event Managed Attributes to FieldMappingConfig
- Collecting Event Managed Attribute now available as a column mapping field in the dropdown
- Fixed Preparation mapping to automatically select Preparation Managed Attribute if the column header matches an existing Preparation Managed Attribute
- Automatically select Collecting Event Managed Attribute if the column header matches an existing Collecting Event Managed Attribute name

35015 Workbook upload add collecting event managed attributes

---

packages/common-ui/lib/api-client/useQuery.tsx
packages/dina-ui/components/revisions/RevisionsPageLayout.tsx

- Fixed the Audit Snapshot link to pass the resource in the URL instead of using the current one.
- Fixed the layout for the error message.
- Fixed revision page details view link and title to use ID from URL.

Support #35047 - Link to audit not working

---

packages/common-ui/lib/instance/InstanceContextProvider.tsx
packages/common-ui/lib/test-util/mock-app-context.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/__snapshots__/MaterialSampleSplitGenerationForm.test.tsx.snap
packages/dina-ui/components/button-bar/nav/nav.tsx
packages/dina-ui/dev.Caddyfile
packages/dina-ui/prod.Caddyfile
packages/dina-ui/test-util/mock-app-context.tsx

- Added instanceName to the instance context.
- Added instanceName to both caddyfiles.
- Updated the URL and it now uses the instanceName to supply the label URL

Support #35084 - Change GitHub feedback url

---

packages/dina-ui/components/tag-editor/TagsAndRestrictionsSection.tsx

- Fixed prop passing, now makes the correct request on the object-store/edit page to get previous tags

35190 search existing on object store tag not working

---

packages/dina-ui/components/seqdb/seq-workflow/SangerSeqReactionStep.tsx
packages/dina-ui/components/seqdb/seq-workflow/__mocks__/SangerRunStepMocks.ts
packages/dina-ui/components/seqdb/seq-workflow/__tests__/SangerRunStep.test.tsx
packages/dina-ui/components/seqdb/seq-workflow/useMolecularAnalysisRun.tsx
packages/dina-ui/types/seqdb-api/resources/MolecularAnalysisRunItem.ts

- Added usageType to the typescript type.
- "seq-reaction" being set for the Sanger Workflow run step on creation.
- Updated mocks and test.
- Also applied it to the SangerSeqReactionStep when adding more when a run already exists. The usageType will be applied.

Support #35223 - Sanger workflow run step needs to set the UsageType

---

packages/dina-ui/components/molecular-analysis/useMetagenomicsWorkflowMolecularAnalysisRun.tsx
packages/dina-ui/components/molecular-analysis/useMolecularAnalysisRun.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/MolecularAnalysisRunStep.tsx
packages/dina-ui/components/seqdb/molecular-analysis-workflow/__tests__/MolecularAnalysisRunStep.test.tsx

- Changed the order of the columns for all workflow run pages (Primary ID and Run item naming first)
- Added a useMemo to the columns so it's only generated on editMode change not on each state change.
- Working on adding test coverage to catch editing both at the same time.

Support #35439 - Improve molecular analysis run page

---

packages/dina-ui/components/molecular-analysis/useMolecularAnalysisRun.tsx

- Identified that the view page was not loading due to molecular-analysis-run having no molecular-analysis-run-item associated
- Normally, this wouldn't be possible through the UI as there is already a check that forces users to select Material Samples as run items
- Implemented a fix that will load the page even if there's no run items

35481 Check why molecular analysis run is not loading

---

packages/dina-ui/components/workbook/column-mapping/WorkbookColumnMapping.tsx
packages/dina-ui/components/workbook/column-mapping/useColumnMapping.tsx
packages/dina-ui/components/workbook/utils/useWorkbookConverter.tsx
packages/dina-ui/components/workbook/utils/workbookMappingUtils.ts

- The problem seemed to be that there was a mismatch of usages of replace() and replaceAll() in the parsing of the workbook column headers to replace "." with "_"
- As a result, for longer column names with multiple ".", only the first occurence was replace() by "_" in some parts while other parts replaceAll()
- I changed everything to use replaceAll() everywhere. This is a bit risky since it refactors other areas as well but it should still work

35417 Collecting event display name workbook relationship mapping issue

---

packages/dina-ui/components/object-store/metadata/useMetadata.tsx
packages/dina-ui/page-tests/object-store/metadata/__tests__/edit.test.tsx

- Fixed test to include derivatives in get request, now without my fix it gets a test failure.
- Fixed the missing derivatives variable (this was accidentallly removed in my unused variables ticket, even though it's unused, it's still removes from the ...metadataValues)

Support #35587 - Issues object store UI

---

packages/common-ui/lib/account/AccountProvider.tsx
packages/common-ui/lib/account/__tests__/AccountProvider.test.tsx

- isAdmin should now evaluate to true if keycloakGroups contains "dina-admin" role but no group

35642 Fix isAdmin logic

---

packages/dina-ui/pages/object-store/object/list.tsx

- Added View Details column to object/list page
- Cannot be removed but can be reordered
- Cannot be exported
- originalFilename column can now be removed
- Clicking on the View Details link should redirect to the object's view page

35387 Add view details meta column to object store list view

---

packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/list-page/query-builder/QueryBuilder.tsx
packages/common-ui/lib/list-page/types.ts

- Saves queryTree as an encoded URI component when user presses the Search button
- QueryPage now parses the URL for an encoded queryTree  parameter and decodes this parameter back into a queryTree
- Pasting the URL with the encoded parameter into a new browser session should populate the query builder with the accordingly

35789 Allow to prefill query builder from url query parameters

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/dina-ui/pages/object-store/object/list.tsx

- Removed original filename as a default option, can still be added using the column selector or exported like before.
- Fixed a QueryPage issue if no local storage exists, it gets stuck loading.
- Fixed issue with additional accessors missing for view details.

Support #36033 - Remove original filename from default columns in object store

---

packages/common-ui/lib/api-client/ApiClientContext.tsx

- Moved interceptor logic to after the setupCache is configured. This fixes the issue with 404 errors not being handled correctly.

Support #36076 - Wait for object export to be ready for download

---

packages/common-ui/lib/column-selector/ColumnSelectorList.tsx
packages/common-ui/lib/export/exportUtils.tsx
packages/common-ui/lib/index.ts
packages/common-ui/lib/list-page-layout/DataExportListPageLayout.tsx
packages/dina-ui/components/collection/material-sample/GenerateLabelDropdownButton.tsx
packages/dina-ui/components/export/useMolecularAnalysisExportAPI.tsx
packages/dina-ui/components/object-store/object-store-utils.ts
packages/dina-ui/pages/export/data-export/export.tsx
packages/dina-ui/pages/export/molecular-analysis-export/export.tsx
packages/dina-ui/pages/workbook/generator.tsx

- Moved downloadDataExport to the export utils.
- Moved the export utils to common UI since it's used across the application.
- Created a downloadBlobFile function since this code was duplicated in multiple spots.
- Fixed issue with tsv not getting a file extension. Now working on chrome + firefox.

Support #36096 - Export tab-separated is not adding extension to export file

---

packages/common-ui/lib/list-page/CopyToClipboardButton.tsx
packages/common-ui/lib/list-page/QueryPage.tsx
packages/common-ui/lib/list-page/query-builder/QueryBuilder.tsx
packages/common-ui/lib/list-page/saved-searches/SavedSearch.tsx
packages/dina-ui/intl/dina-ui-en.ts

- Implemented new CopyToClipboardButton
- Added CopyToClipboard button next to Search/Reset buttons in QueryBuilder
- Clicking on the button should copy the whole URL with the queryTree to clipboard

36029 Add option to generate query tree URL on the query page

---

packages/common-ui/lib/list-page/QueryPage.tsx

- Fixed bug where URL filter was being applied but the QueryBuilder did not reflect the queryTree
- The QueryBuilder should not reflect the URL's queryTree on load

36104 Query filters not populated by url

---

packages/common-ui/lib/column-selector/ColumnSelector.tsx
packages/common-ui/lib/column-selector/ColumnSelectorUtils.tsx
packages/dina-ui/pages/export/data-export/export.tsx
packages/dina-ui/pages/export/data-export/useSavedExports.tsx

- Fixed logic to include columnFunctions in data-export-template POST/PATCH requests
- Now correctly saves columnFunctions to backend
- Fixed logic to load columnFunctions when selecting a saved data-export-template
- Now correctly creates a column definition for columnFunctions and exporting should work

35957 SRA Export Template not saving functions to template

---

packages/dina-ui/components/export/useMolecularAnalysisExportAPI.tsx

- Changed logic to group results into one folder and qa's into one folder

36109 Don't put attachments in subfolders for molecular analysis workflow exports

---

packages/common-ui/lib/api-client/ApiClientContext.tsx
packages/common-ui/lib/api-client/__mocks__/ApiClientContextMocks.ts
packages/common-ui/lib/api-client/__tests__/ApiClientContext.test.ts

-added error handling for 404 and 410 errors in the bulkLoadResources function
-added unit tests for said error handling
-when returnNullForMissingResources is enabled, the api request will be re-run without the error-causing requested ids up a maximum of three times, since 404 and 410 errors cannot be returned at the same time

added error handling and tests to bulkLoadResources

---

packages/common-ui/lib/api-client/ApiClientContext.tsx
packages/dina-ui/components/bulk-edit/__tests__/useBulkEditTab.test.tsx
packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/collection/material-sample/__tests__/MaterialSampleForm.test.tsx
packages/dina-ui/components/managed-attributes/ManagedAttributesEditor.tsx
packages/dina-ui/components/managed-attributes/__tests__/ManagedAttributesEditor.test.tsx
packages/dina-ui/components/managed-attributes/useManagedAttributeQueries.tsx
packages/dina-ui/page-tests/collection/collecting-event/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/collection-method/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/preparation-method/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/preparation-type/__test__/edit.test.tsx
packages/dina-ui/page-tests/collection/protocol/__test__/edit.test.tsx
packages/dina-ui/page-tests/object-store/metadata/__tests__/edit.test.tsx

-collection-api now uses skipOperationForSingleRequest for all doOperations calls
-fixed unit tests that broke as a result of this change
-added new hook in managedAttributeEditor that does parallel single queries using keys for managedAttributes

Support #36502 adapt UI code for collection api v2 managed attributes

---

packages/dina-ui/components/bulk-material-sample/__tests__/MaterialSampleBulkEditor.test.tsx
packages/dina-ui/components/storage/StorageSearchSelector.tsx
packages/dina-ui/components/storage/__tests__/StorageUnitChildrenViewer.test.tsx
packages/dina-ui/intl/dina-ui-en.ts

-changed storageSearchSelector to use queryPage instead of QueryTable
-set unit test for moving all stored samples and storages to another storage unit to skip since the functionality was broken before this branch was created and is not in scope for this ticket.

Support #36550 add barcode to storage search from material sample
